
```{r setup}
library(tidyverse)
library(ggthemes)

rm(list = ls())

load("files/data_final.RData")

data <- data %>% group_by(person_id) %>% filter(min(age) == 50) %>% filter(country == "Germany")
```

```{r}
gender <- data %>% group_by(person_id) %>% filter(age == max(age)) %>% group_by(sex) %>% summarise(share = n()) %>% mutate(variable = "Gender")
homeowner <- data %>% group_by(person_id) %>% filter(age == max(age)) %>% group_by(homeowner_type) %>% summarise(share = n()) %>% mutate(variable = "Tenure status")
retired <- data %>% group_by(person_id) %>% filter(age == max(age)) %>% group_by(retired) %>% summarise(share = n()) %>% mutate(variable = "Retired")

ggplot() +
  geom_bar(data = retired, aes(x = variable, y = (share)/sum(share), fill = as.factor(retired)), position = "stack", stat = "identity") +
  geom_bar(data = gender, aes(x = variable, y = (share)/sum(share), fill = as.factor(sex)), position = "stack", stat = "identity") +
  geom_bar(data = homeowner, aes(x = variable, y = (share)/sum(share), fill = as.factor(homeowner_type)), position = "stack", stat = "identity") +
  coord_flip() +
  scale_fill_brewer(palette = "Spectral") +
  scale_y_continuous("", labels = scales::percent) +
  scale_x_discrete("") +
  theme_classic() +
  theme(strip.placement = 'outside',
        strip.background = element_blank(),
        legend.position = "top",
        legend.title = element_blank())
ggsave("descriptive_stats_1.png", height = 4, width = 8)

rm(gender, homeowner, retired)
```

```{r}
test <- data %>% 
  group_by(age) %>% 
  summarise(
    total = n(),
    retired = sum(retired),
    not_retired = total - retired) %>%
  select(-total) %>%
  pivot_longer(!age)

ggplot(test, aes(x = age, fill = name)) +
  geom_bar(aes(y = value), stat = "identity") +
  scale_y_continuous("", breaks = seq(0, 20000, 1000)) +
  scale_x_continuous("", breaks = seq(50, 70, 2)) +
  theme_classic() +
  theme(strip.placement = 'outside',
        strip.background = element_blank(),
        legend.position = "none",
        legend.title = element_blank()) +
  scale_fill_brewer(palette = "Spectral")
ggsave("descriptive_stats_2.png", height = 4, width = 4)
```

```{r}
homeowner
(4663 + 5537) / (2885 + 5537 + 4663) * 100
```