---
title: "1_data"
---

```{r setup}
# Load packages
library("tidyverse")
library("lmtp")
library("future")
library("lubridate")
library("listenv")
library("SuperLearner")

# Avoid exponential notation in numbers
options("scipen" = 100, "digits" = 4)

# Clear workspace
rm(list = ls())

# Set global seed
set.seed(999)

# Load data
load("data/data_de_final.RData")

```

```{r}
# Choose data from imputed data sets, set density ratio trimming and folds, and select SuperLearner libraries
data_wide <- data_de_imp_wide_1
last_age <- 65
trim <- 0.99
folds <- 5
SL_folds <- 5
SL_libs <- c("SL.xgboost", "SL.ranger", "SL.earth")

```

```{r, warning = F}
start <- Sys.time()

# Create containers for results
results_homeowners <- listenv()
results_renters <- listenv()

# Set up parallel computing
plan(multisession, workers = availableCores())

# Iterate through age range
#for (i in c(last_age:51)) {
for (i in c(53)) {

# Define treatment, outcome, censoring, and confounder variables
treatment <- paste0("T1_", 50:(i - 1))
outcome <- paste0("Y_", 51:i)
censoring <- paste0("C_", 50:(i - 1))
baseline <- c("B1", "B2", "B3", "B4")

vars <- data_wide %>% select(starts_with(c("L"))) %>% names() 

time_vary = list()

for (tp in c(50:(i - 1))) {
  time_vary_new <- c(vars[str_detect(vars, str_pad(tp, 2, pad = "0"))])
  
  time_vary[[length(time_vary) + 1]] <- time_vary_new}

  # Initialize TMLE for renters aged i# Initialize TMLE for renters aged i
  results_renters[[i]] %<-% {lmtp_tmle(data_wide,
                                       trt = treatment,
                                       outcome = outcome,
                                       baseline = baseline,
                                       time_vary = time_vary,
                                       cens = censoring,
                                       shift = function(data, trt) {return("Renter")},
                                       outcome_type = ifelse(i == 51, "binomial", "survival"),
                                       learners_outcome = SL_libs,
                                       learners_trt = SL_libs,
                                       folds = folds,
                                       .trim = trim,
                                       .learners_outcome_folds = SL_folds,
                                       .learners_trt_folds = SL_folds)}

  # Initialize TMLE for homeowners aged i
  results_homeowners[[i]] %<-% {lmtp_tmle(data_wide,
                                          trt = treatment,
                                          outcome = outcome,
                                          baseline = baseline,
                                          time_vary = time_vary,
                                          cens = censoring,
                                          shift = function(data, trt) {return("Homeowner")},
                                          outcome_type = ifelse(i == 51, "binomial", "survival"),
                                          learners_outcome = SL_libs,
                                          learners_trt = SL_libs,
                                          folds = folds,
                                          .trim = trim,
                                          .learners_outcome_folds = SL_folds,
                                          .learners_trt_folds = SL_folds)}

  print(paste0("Initialized TMLE for age ", i, "."))

  rm(time_vary_new, tp)

}

# Gather results
results_homeowners <- as.list(results_homeowners)
results_renters <- as.list(results_renters)

end <- Sys.time()

print(paste0("Estimation completed at ", paste(hour(end), minute(end), sep = ":"), " after ", round(difftime(end, start, units = "mins"), 0), " minutes."))

rm(treatment, outcome, censoring, time_vary, baseline, i, start, end)

```

```{r}
contrasts <- data.frame()
  
results <- data.frame()

for (i in c(last_age:51)) {
  
  cntr <- lmtp_contrast(results_homeowners[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts <- rbind(contrasts, cntr$vals)
  
  rslt <- tidy(results_homeowners[[i]])
  rslt$age <- i
  rslt$group <- "Homeowners"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_renters[[i]])
  rslt$age <- i
  rslt$group <- "Renters"
  results <- rbind(results, rslt)
  
  rm(cntr, rslt)
  
}

# convert probability estimate at age 51 into survival
contrasts$age <- c(last_age:51)
contrasts$theta <- ifelse(contrasts$age == 51, (-1) * contrasts$theta, contrasts$theta)
contrasts$conf.low <- ifelse(contrasts$age == 51, (-1) * contrasts$conf.low, contrasts$conf.low)
contrasts$conf.high <- ifelse(contrasts$age == 51, (-1) * contrasts$conf.high, contrasts$conf.high)

results$estimate <- ifelse(results$age == 51, 1 - results$estimate, results$estimate)
results$conf.low <- ifelse(results$age == 51, 1 - results$conf.low, results$conf.low)
results$conf.high <- ifelse(results$age == 51, 1 - results$conf.high, results$conf.high)

rm(i, last_age, results_homeowners, results_renters)

```

```{r}
save.image("outputs/results_de_imp1.RData")

```

```{r}
```
