---
title: "2.2_analysis"
---

```{r setup}
# Load packages
library("tidyverse")
library("lmtp")
library("future")
library("lubridate")
library("listenv")
library("SuperLearner")

# Avoid exponential notation in numbers
options("scipen" = 100, "digits" = 4)

# Clear workspace
rm(list = ls())

# Set global seed
set.seed(999)

# Set last age, truncation and folds, and select SuperLearner models
last_age <- 65
trim <- 0.975
folds <- 3
SL_folds <- 3
SL_libs <- c("SL.ranger")

```

# uk - Imp 1
```{r}

# Load data and choose from imputed data sets
load("data/data_final_uk.RData")

data_wide <- data_uk_imp_wide_2

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs")))

data_wide <- data_wide %>% select(-starts_with(c("T1", "T3")))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~as.character(.)))

data_wide <- data_wide %>%
  mutate(T2_50 = case_when(T2_50 == "Outright owner" ~ "1", T2_50 == "Mortgagor" ~ "2", T2_50 == "Renter" ~ "3")) %>%
  mutate(T2_51 = case_when(T2_51 == "Outright owner" ~ "1", T2_51 == "Mortgagor" ~ "2", T2_51 == "Renter" ~ "3")) %>%
  mutate(T2_52 = case_when(T2_52 == "Outright owner" ~ "1", T2_52 == "Mortgagor" ~ "2", T2_52 == "Renter" ~ "3")) %>%
  mutate(T2_53 = case_when(T2_53 == "Outright owner" ~ "1", T2_53 == "Mortgagor" ~ "2", T2_53 == "Renter" ~ "3")) %>%
  mutate(T2_54 = case_when(T2_54 == "Outright owner" ~ "1", T2_54 == "Mortgagor" ~ "2", T2_54 == "Renter" ~ "3")) %>%
  mutate(T2_55 = case_when(T2_55 == "Outright owner" ~ "1", T2_55 == "Mortgagor" ~ "2", T2_55 == "Renter" ~ "3")) %>%
  mutate(T2_56 = case_when(T2_56 == "Outright owner" ~ "1", T2_56 == "Mortgagor" ~ "2", T2_56 == "Renter" ~ "3")) %>%
  mutate(T2_57 = case_when(T2_57 == "Outright owner" ~ "1", T2_57 == "Mortgagor" ~ "2", T2_57 == "Renter" ~ "3")) %>%
  mutate(T2_58 = case_when(T2_58 == "Outright owner" ~ "1", T2_58 == "Mortgagor" ~ "2", T2_58 == "Renter" ~ "3")) %>%
  mutate(T2_59 = case_when(T2_59 == "Outright owner" ~ "1", T2_59 == "Mortgagor" ~ "2", T2_59 == "Renter" ~ "3")) %>%
  mutate(T2_60 = case_when(T2_60 == "Outright owner" ~ "1", T2_60 == "Mortgagor" ~ "2", T2_60 == "Renter" ~ "3")) %>%
  mutate(T2_61 = case_when(T2_61 == "Outright owner" ~ "1", T2_61 == "Mortgagor" ~ "2", T2_61 == "Renter" ~ "3")) %>%
  mutate(T2_62 = case_when(T2_62 == "Outright owner" ~ "1", T2_62 == "Mortgagor" ~ "2", T2_62 == "Renter" ~ "3")) %>%
  mutate(T2_63 = case_when(T2_63 == "Outright owner" ~ "1", T2_63 == "Mortgagor" ~ "2", T2_63 == "Renter" ~ "3")) %>%
  mutate(T2_64 = case_when(T2_64 == "Outright owner" ~ "1", T2_64 == "Mortgagor" ~ "2", T2_64 == "Renter" ~ "3")) %>%
  mutate(T2_65 = case_when(T2_65 == "Outright owner" ~ "1", T2_65 == "Mortgagor" ~ "2", T2_65 == "Renter" ~ "3"))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~factor(., levels = 0:3)))

# Save start time
start <- Sys.time()

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs", "start")))

# Create containers for results
results_renters <- listenv()
results_outright <- listenv()
results_mortgage <- listenv()

# Set up parallel computing with max 30 cores
workers <- as.numeric(availableCores())
workers <- pmin(45, workers)

plan(multisession, workers = workers)

# Iterate through age range
for (i in c(60)) {

# Define treatment, outcome, censoring, and confounder variables
treatment <- paste0("T2_", 50:(i - 1))
outcome <- paste0("Y_", 51:i)
censoring <- paste0("C_", 50:(i - 1))
baseline <- c("B1", "B2", "B3", "B4")

vars <- data_wide %>% select(starts_with(c("L"))) %>% names()

time_vary = list()

for (tp in c(50:(i - 1))) {
  time_vary_new <- c(vars[str_detect(vars, str_pad(tp, 2, pad = "0"))])
  
  time_vary[[length(time_vary) + 1]] <- time_vary_new}

  # Initialize TMLE for renters aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "2", "3", "3"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))

  results_renters[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  # Initialize TMLE for outright owners aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "2" | . == "3", "1", "1"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_outright[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}
  
  # Initialize TMLE for mortgagors aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "3", "2", "2"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_mortgage[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  print(paste0("Initialized TMLE for age ", i, "."))

  rm(time_vary_new, tp, shifted)

}

# Gather results
results_renters <- as.list(results_renters)
results_outright <- as.list(results_outright)
results_mortgage <- as.list(results_mortgage)

end <- Sys.time()

print(paste0("Estimation completed at ", paste(hour(end), minute(end), sep = ":"), " after ", round(difftime(end, start, units = "mins"), 0), " minutes."))

rm(treatment, outcome, censoring, time_vary, baseline, workers, i, start, end)

# Clean results
contrasts_outright <- data.frame()
contrasts_mortgage <- data.frame()
results <- data.frame()

for (i in c(60)) {
  
  cntr <- lmtp_contrast(results_outright[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_outright <- rbind(contrasts_outright, cntr$vals)
  
  cntr <- lmtp_contrast(results_mortgage[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_mortgage <- rbind(contrasts_mortgage, cntr$vals)
  
  rslt <- tidy(results_renters[[i]])
  rslt$age <- i
  rslt$group <- "Renters"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_outright[[i]])
  rslt$age <- i
  rslt$group <- "Outright owners"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_mortgage[[i]])
  rslt$age <- i
  rslt$group <- "Owner w/ mortgage"
  results <- rbind(results, rslt)
  
  rm(cntr, rslt)
  
}

# Covert probability estimate at age 51 into survival
contrasts_outright$age <- c(51:60)
contrasts_outright$theta <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$theta, contrasts_outright$theta)
contrasts_outright$conf.low <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.low, contrasts_outright$conf.low)
contrasts_outright$conf.high <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.high, contrasts_outright$conf.high)

contrasts_mortgage$age <- c(51:60)
contrasts_mortgage$theta <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$theta, contrasts_mortgage$theta)
contrasts_mortgage$conf.low <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.low, contrasts_mortgage$conf.low)
contrasts_mortgage$conf.high <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.high, contrasts_mortgage$conf.high)

results$estimate <- ifelse(results$age == 51, 1 - results$estimate, results$estimate)
results$conf.low <- ifelse(results$age == 51, 1 - results$conf.low, results$conf.low)
results$conf.high <- ifelse(results$age == 51, 1 - results$conf.high, results$conf.high)

rm(i)

results

```

# uk - Imp 2
```{r}

# Load data and choose from imputed data sets
load("data/data_final_uk.RData")

data_wide <- data_uk_imp_wide_2

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs")))

data_wide <- data_wide %>% select(-starts_with(c("T1", "T3")))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~as.character(.)))

data_wide <- data_wide %>%
  mutate(T2_50 = case_when(T2_50 == "Outright owner" ~ "1", T2_50 == "Mortgagor" ~ "2", T2_50 == "Renter" ~ "3")) %>%
  mutate(T2_51 = case_when(T2_51 == "Outright owner" ~ "1", T2_51 == "Mortgagor" ~ "2", T2_51 == "Renter" ~ "3")) %>%
  mutate(T2_52 = case_when(T2_52 == "Outright owner" ~ "1", T2_52 == "Mortgagor" ~ "2", T2_52 == "Renter" ~ "3")) %>%
  mutate(T2_53 = case_when(T2_53 == "Outright owner" ~ "1", T2_53 == "Mortgagor" ~ "2", T2_53 == "Renter" ~ "3")) %>%
  mutate(T2_54 = case_when(T2_54 == "Outright owner" ~ "1", T2_54 == "Mortgagor" ~ "2", T2_54 == "Renter" ~ "3")) %>%
  mutate(T2_55 = case_when(T2_55 == "Outright owner" ~ "1", T2_55 == "Mortgagor" ~ "2", T2_55 == "Renter" ~ "3")) %>%
  mutate(T2_56 = case_when(T2_56 == "Outright owner" ~ "1", T2_56 == "Mortgagor" ~ "2", T2_56 == "Renter" ~ "3")) %>%
  mutate(T2_57 = case_when(T2_57 == "Outright owner" ~ "1", T2_57 == "Mortgagor" ~ "2", T2_57 == "Renter" ~ "3")) %>%
  mutate(T2_58 = case_when(T2_58 == "Outright owner" ~ "1", T2_58 == "Mortgagor" ~ "2", T2_58 == "Renter" ~ "3")) %>%
  mutate(T2_59 = case_when(T2_59 == "Outright owner" ~ "1", T2_59 == "Mortgagor" ~ "2", T2_59 == "Renter" ~ "3")) %>%
  mutate(T2_60 = case_when(T2_60 == "Outright owner" ~ "1", T2_60 == "Mortgagor" ~ "2", T2_60 == "Renter" ~ "3")) %>%
  mutate(T2_61 = case_when(T2_61 == "Outright owner" ~ "1", T2_61 == "Mortgagor" ~ "2", T2_61 == "Renter" ~ "3")) %>%
  mutate(T2_62 = case_when(T2_62 == "Outright owner" ~ "1", T2_62 == "Mortgagor" ~ "2", T2_62 == "Renter" ~ "3")) %>%
  mutate(T2_63 = case_when(T2_63 == "Outright owner" ~ "1", T2_63 == "Mortgagor" ~ "2", T2_63 == "Renter" ~ "3")) %>%
  mutate(T2_64 = case_when(T2_64 == "Outright owner" ~ "1", T2_64 == "Mortgagor" ~ "2", T2_64 == "Renter" ~ "3")) %>%
  mutate(T2_65 = case_when(T2_65 == "Outright owner" ~ "1", T2_65 == "Mortgagor" ~ "2", T2_65 == "Renter" ~ "3"))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~factor(., levels = 0:3)))

# Save start time
start <- Sys.time()

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs", "start")))

# Create containers for results
results_renters <- listenv()
results_outright <- listenv()
results_mortgage <- listenv()

# Set up parallel computing with max 30 cores
workers <- as.numeric(availableCores())
workers <- pmin(45, workers)

plan(multisession, workers = workers)

# Iterate through age range
for (i in c(last_age:51)) {

# Define treatment, outcome, censoring, and confounder variables
treatment <- paste0("T2_", 50:(i - 1))
outcome <- paste0("Y_", 51:i)
censoring <- paste0("C_", 50:(i - 1))
baseline <- c("B1", "B2", "B3", "B4")

vars <- data_wide %>% select(starts_with(c("L"))) %>% names()

time_vary = list()

for (tp in c(50:(i - 1))) {
  time_vary_new <- c(vars[str_detect(vars, str_pad(tp, 2, pad = "0"))])
  
  time_vary[[length(time_vary) + 1]] <- time_vary_new}

  # Initialize TMLE for renters aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "2", "3", "3"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))

  results_renters[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  # Initialize TMLE for outright owners aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "2" | . == "3", "1", "1"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_outright[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}
  
  # Initialize TMLE for mortgagors aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "3", "2", "2"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_mortgage[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  print(paste0("Initialized TMLE for age ", i, "."))

  rm(time_vary_new, tp, shifted)

}

# Gather results
results_renters <- as.list(results_renters)
results_outright <- as.list(results_outright)
results_mortgage <- as.list(results_mortgage)

end <- Sys.time()

print(paste0("Estimation completed at ", paste(hour(end), minute(end), sep = ":"), " after ", round(difftime(end, start, units = "mins"), 0), " minutes."))

rm(treatment, outcome, censoring, time_vary, baseline, workers, i, start, end)

# Clean results
contrasts_outright <- data.frame()
contrasts_mortgage <- data.frame()
results <- data.frame()

for (i in c(51:last_age)) {
  
  cntr <- lmtp_contrast(results_outright[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_outright <- rbind(contrasts_outright, cntr$vals)
  
  cntr <- lmtp_contrast(results_mortgage[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_mortgage <- rbind(contrasts_mortgage, cntr$vals)
  
  rslt <- tidy(results_renters[[i]])
  rslt$age <- i
  rslt$group <- "Renters"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_outright[[i]])
  rslt$age <- i
  rslt$group <- "Outright owners"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_mortgage[[i]])
  rslt$age <- i
  rslt$group <- "Owner w/ mortgage"
  results <- rbind(results, rslt)
  
  rm(cntr, rslt)
  
}

# Covert probability estimate at age 51 into survival
contrasts_outright$age <- c(51:last_age)
contrasts_outright$theta <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$theta, contrasts_outright$theta)
contrasts_outright$conf.low <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.low, contrasts_outright$conf.low)
contrasts_outright$conf.high <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.high, contrasts_outright$conf.high)

contrasts_mortgage$age <- c(51:last_age)
contrasts_mortgage$theta <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$theta, contrasts_mortgage$theta)
contrasts_mortgage$conf.low <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.low, contrasts_mortgage$conf.low)
contrasts_mortgage$conf.high <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.high, contrasts_mortgage$conf.high)

results$estimate <- ifelse(results$age == 51, 1 - results$estimate, results$estimate)
results$conf.low <- ifelse(results$age == 51, 1 - results$conf.low, results$conf.low)
results$conf.high <- ifelse(results$age == 51, 1 - results$conf.high, results$conf.high)

rm(i)

#Save results
save.image("outputs/results_imps2/results_uk_2_imp2.RData")

```

# uk - Imp 3
```{r}

# Load data and choose from imputed data sets
load("data/data_final_uk.RData")

data_wide <- data_uk_imp_wide_3

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs")))

data_wide <- data_wide %>% select(-starts_with(c("T1", "T3")))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~as.character(.)))

data_wide <- data_wide %>%
  mutate(T2_50 = case_when(T2_50 == "Outright owner" ~ "1", T2_50 == "Mortgagor" ~ "2", T2_50 == "Renter" ~ "3")) %>%
  mutate(T2_51 = case_when(T2_51 == "Outright owner" ~ "1", T2_51 == "Mortgagor" ~ "2", T2_51 == "Renter" ~ "3")) %>%
  mutate(T2_52 = case_when(T2_52 == "Outright owner" ~ "1", T2_52 == "Mortgagor" ~ "2", T2_52 == "Renter" ~ "3")) %>%
  mutate(T2_53 = case_when(T2_53 == "Outright owner" ~ "1", T2_53 == "Mortgagor" ~ "2", T2_53 == "Renter" ~ "3")) %>%
  mutate(T2_54 = case_when(T2_54 == "Outright owner" ~ "1", T2_54 == "Mortgagor" ~ "2", T2_54 == "Renter" ~ "3")) %>%
  mutate(T2_55 = case_when(T2_55 == "Outright owner" ~ "1", T2_55 == "Mortgagor" ~ "2", T2_55 == "Renter" ~ "3")) %>%
  mutate(T2_56 = case_when(T2_56 == "Outright owner" ~ "1", T2_56 == "Mortgagor" ~ "2", T2_56 == "Renter" ~ "3")) %>%
  mutate(T2_57 = case_when(T2_57 == "Outright owner" ~ "1", T2_57 == "Mortgagor" ~ "2", T2_57 == "Renter" ~ "3")) %>%
  mutate(T2_58 = case_when(T2_58 == "Outright owner" ~ "1", T2_58 == "Mortgagor" ~ "2", T2_58 == "Renter" ~ "3")) %>%
  mutate(T2_59 = case_when(T2_59 == "Outright owner" ~ "1", T2_59 == "Mortgagor" ~ "2", T2_59 == "Renter" ~ "3")) %>%
  mutate(T2_60 = case_when(T2_60 == "Outright owner" ~ "1", T2_60 == "Mortgagor" ~ "2", T2_60 == "Renter" ~ "3")) %>%
  mutate(T2_61 = case_when(T2_61 == "Outright owner" ~ "1", T2_61 == "Mortgagor" ~ "2", T2_61 == "Renter" ~ "3")) %>%
  mutate(T2_62 = case_when(T2_62 == "Outright owner" ~ "1", T2_62 == "Mortgagor" ~ "2", T2_62 == "Renter" ~ "3")) %>%
  mutate(T2_63 = case_when(T2_63 == "Outright owner" ~ "1", T2_63 == "Mortgagor" ~ "2", T2_63 == "Renter" ~ "3")) %>%
  mutate(T2_64 = case_when(T2_64 == "Outright owner" ~ "1", T2_64 == "Mortgagor" ~ "2", T2_64 == "Renter" ~ "3")) %>%
  mutate(T2_65 = case_when(T2_65 == "Outright owner" ~ "1", T2_65 == "Mortgagor" ~ "2", T2_65 == "Renter" ~ "3"))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~factor(., levels = 0:3)))

# Save start time
start <- Sys.time()

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs", "start")))

# Create containers for results
results_renters <- listenv()
results_outright <- listenv()
results_mortgage <- listenv()

# Set up parallel computing with max 30 cores
workers <- as.numeric(availableCores())
workers <- pmin(45, workers)

plan(multisession, workers = workers)

# Iterate through age range
for (i in c(last_age:51)) {

# Define treatment, outcome, censoring, and confounder variables
treatment <- paste0("T2_", 50:(i - 1))
outcome <- paste0("Y_", 51:i)
censoring <- paste0("C_", 50:(i - 1))
baseline <- c("B1", "B2", "B3", "B4")

vars <- data_wide %>% select(starts_with(c("L"))) %>% names()

time_vary = list()

for (tp in c(50:(i - 1))) {
  time_vary_new <- c(vars[str_detect(vars, str_pad(tp, 2, pad = "0"))])
  
  time_vary[[length(time_vary) + 1]] <- time_vary_new}

  # Initialize TMLE for renters aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "2", "3", "3"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))

  results_renters[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  # Initialize TMLE for outright owners aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "2" | . == "3", "1", "1"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_outright[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}
  
  # Initialize TMLE for mortgagors aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "3", "2", "2"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_mortgage[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  print(paste0("Initialized TMLE for age ", i, "."))

  rm(time_vary_new, tp, shifted)

}

# Gather results
results_renters <- as.list(results_renters)
results_outright <- as.list(results_outright)
results_mortgage <- as.list(results_mortgage)

end <- Sys.time()

print(paste0("Estimation completed at ", paste(hour(end), minute(end), sep = ":"), " after ", round(difftime(end, start, units = "mins"), 0), " minutes."))

rm(treatment, outcome, censoring, time_vary, baseline, workers, i, start, end)

# Clean results
contrasts_outright <- data.frame()
contrasts_mortgage <- data.frame()
results <- data.frame()

for (i in c(51:last_age)) {
  
  cntr <- lmtp_contrast(results_outright[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_outright <- rbind(contrasts_outright, cntr$vals)
  
  cntr <- lmtp_contrast(results_mortgage[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_mortgage <- rbind(contrasts_mortgage, cntr$vals)
  
  rslt <- tidy(results_renters[[i]])
  rslt$age <- i
  rslt$group <- "Renters"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_outright[[i]])
  rslt$age <- i
  rslt$group <- "Outright owners"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_mortgage[[i]])
  rslt$age <- i
  rslt$group <- "Owner w/ mortgage"
  results <- rbind(results, rslt)
  
  rm(cntr, rslt)
  
}

# Covert probability estimate at age 51 into survival
contrasts_outright$age <- c(51:last_age)
contrasts_outright$theta <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$theta, contrasts_outright$theta)
contrasts_outright$conf.low <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.low, contrasts_outright$conf.low)
contrasts_outright$conf.high <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.high, contrasts_outright$conf.high)

contrasts_mortgage$age <- c(51:last_age)
contrasts_mortgage$theta <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$theta, contrasts_mortgage$theta)
contrasts_mortgage$conf.low <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.low, contrasts_mortgage$conf.low)
contrasts_mortgage$conf.high <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.high, contrasts_mortgage$conf.high)

results$estimate <- ifelse(results$age == 51, 1 - results$estimate, results$estimate)
results$conf.low <- ifelse(results$age == 51, 1 - results$conf.low, results$conf.low)
results$conf.high <- ifelse(results$age == 51, 1 - results$conf.high, results$conf.high)

rm(i)

#Save results
save.image("outputs/results_imps2/results_uk_2_imp3.RData")

```

# uk - Imp 4
```{r}

# Load data and choose from imputed data sets
load("data/data_final_uk.RData")

data_wide <- data_uk_imp_wide_4

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs")))

data_wide <- data_wide %>% select(-starts_with(c("T1", "T3")))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~as.character(.)))

data_wide <- data_wide %>%
  mutate(T2_50 = case_when(T2_50 == "Outright owner" ~ "1", T2_50 == "Mortgagor" ~ "2", T2_50 == "Renter" ~ "3")) %>%
  mutate(T2_51 = case_when(T2_51 == "Outright owner" ~ "1", T2_51 == "Mortgagor" ~ "2", T2_51 == "Renter" ~ "3")) %>%
  mutate(T2_52 = case_when(T2_52 == "Outright owner" ~ "1", T2_52 == "Mortgagor" ~ "2", T2_52 == "Renter" ~ "3")) %>%
  mutate(T2_53 = case_when(T2_53 == "Outright owner" ~ "1", T2_53 == "Mortgagor" ~ "2", T2_53 == "Renter" ~ "3")) %>%
  mutate(T2_54 = case_when(T2_54 == "Outright owner" ~ "1", T2_54 == "Mortgagor" ~ "2", T2_54 == "Renter" ~ "3")) %>%
  mutate(T2_55 = case_when(T2_55 == "Outright owner" ~ "1", T2_55 == "Mortgagor" ~ "2", T2_55 == "Renter" ~ "3")) %>%
  mutate(T2_56 = case_when(T2_56 == "Outright owner" ~ "1", T2_56 == "Mortgagor" ~ "2", T2_56 == "Renter" ~ "3")) %>%
  mutate(T2_57 = case_when(T2_57 == "Outright owner" ~ "1", T2_57 == "Mortgagor" ~ "2", T2_57 == "Renter" ~ "3")) %>%
  mutate(T2_58 = case_when(T2_58 == "Outright owner" ~ "1", T2_58 == "Mortgagor" ~ "2", T2_58 == "Renter" ~ "3")) %>%
  mutate(T2_59 = case_when(T2_59 == "Outright owner" ~ "1", T2_59 == "Mortgagor" ~ "2", T2_59 == "Renter" ~ "3")) %>%
  mutate(T2_60 = case_when(T2_60 == "Outright owner" ~ "1", T2_60 == "Mortgagor" ~ "2", T2_60 == "Renter" ~ "3")) %>%
  mutate(T2_61 = case_when(T2_61 == "Outright owner" ~ "1", T2_61 == "Mortgagor" ~ "2", T2_61 == "Renter" ~ "3")) %>%
  mutate(T2_62 = case_when(T2_62 == "Outright owner" ~ "1", T2_62 == "Mortgagor" ~ "2", T2_62 == "Renter" ~ "3")) %>%
  mutate(T2_63 = case_when(T2_63 == "Outright owner" ~ "1", T2_63 == "Mortgagor" ~ "2", T2_63 == "Renter" ~ "3")) %>%
  mutate(T2_64 = case_when(T2_64 == "Outright owner" ~ "1", T2_64 == "Mortgagor" ~ "2", T2_64 == "Renter" ~ "3")) %>%
  mutate(T2_65 = case_when(T2_65 == "Outright owner" ~ "1", T2_65 == "Mortgagor" ~ "2", T2_65 == "Renter" ~ "3"))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~factor(., levels = 0:3)))

# Save start time
start <- Sys.time()

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs", "start")))

# Create containers for results
results_renters <- listenv()
results_outright <- listenv()
results_mortgage <- listenv()

# Set up parallel computing with max 30 cores
workers <- as.numeric(availableCores())
workers <- pmin(45, workers)

plan(multisession, workers = workers)

# Iterate through age range
for (i in c(last_age:51)) {

# Define treatment, outcome, censoring, and confounder variables
treatment <- paste0("T2_", 50:(i - 1))
outcome <- paste0("Y_", 51:i)
censoring <- paste0("C_", 50:(i - 1))
baseline <- c("B1", "B2", "B3", "B4")

vars <- data_wide %>% select(starts_with(c("L"))) %>% names()

time_vary = list()

for (tp in c(50:(i - 1))) {
  time_vary_new <- c(vars[str_detect(vars, str_pad(tp, 2, pad = "0"))])
  
  time_vary[[length(time_vary) + 1]] <- time_vary_new}

  # Initialize TMLE for renters aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "2", "3", "3"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))

  results_renters[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  # Initialize TMLE for outright owners aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "2" | . == "3", "1", "1"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_outright[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}
  
  # Initialize TMLE for mortgagors aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "3", "2", "2"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_mortgage[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  print(paste0("Initialized TMLE for age ", i, "."))

  rm(time_vary_new, tp, shifted)

}

# Gather results
results_renters <- as.list(results_renters)
results_outright <- as.list(results_outright)
results_mortgage <- as.list(results_mortgage)

end <- Sys.time()

print(paste0("Estimation completed at ", paste(hour(end), minute(end), sep = ":"), " after ", round(difftime(end, start, units = "mins"), 0), " minutes."))

rm(treatment, outcome, censoring, time_vary, baseline, workers, i, start, end)

# Clean results
contrasts_outright <- data.frame()
contrasts_mortgage <- data.frame()
results <- data.frame()

for (i in c(51:last_age)) {
  
  cntr <- lmtp_contrast(results_outright[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_outright <- rbind(contrasts_outright, cntr$vals)
  
  cntr <- lmtp_contrast(results_mortgage[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_mortgage <- rbind(contrasts_mortgage, cntr$vals)
  
  rslt <- tidy(results_renters[[i]])
  rslt$age <- i
  rslt$group <- "Renters"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_outright[[i]])
  rslt$age <- i
  rslt$group <- "Outright owners"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_mortgage[[i]])
  rslt$age <- i
  rslt$group <- "Owner w/ mortgage"
  results <- rbind(results, rslt)
  
  rm(cntr, rslt)
  
}

# Covert probability estimate at age 51 into survival
contrasts_outright$age <- c(51:last_age)
contrasts_outright$theta <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$theta, contrasts_outright$theta)
contrasts_outright$conf.low <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.low, contrasts_outright$conf.low)
contrasts_outright$conf.high <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.high, contrasts_outright$conf.high)

contrasts_mortgage$age <- c(51:last_age)
contrasts_mortgage$theta <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$theta, contrasts_mortgage$theta)
contrasts_mortgage$conf.low <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.low, contrasts_mortgage$conf.low)
contrasts_mortgage$conf.high <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.high, contrasts_mortgage$conf.high)

results$estimate <- ifelse(results$age == 51, 1 - results$estimate, results$estimate)
results$conf.low <- ifelse(results$age == 51, 1 - results$conf.low, results$conf.low)
results$conf.high <- ifelse(results$age == 51, 1 - results$conf.high, results$conf.high)

rm(i)

#Save results
save.image("outputs/results_imps2/results_uk_2_imp4.RData")

```

# uk - Imp 5
```{r}

# Load data and choose from imputed data sets
load("data/data_final_uk.RData")

data_wide <- data_uk_imp_wide_5

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs")))

data_wide <- data_wide %>% select(-starts_with(c("T1", "T3")))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~as.character(.)))

data_wide <- data_wide %>%
  mutate(T2_50 = case_when(T2_50 == "Outright owner" ~ "1", T2_50 == "Mortgagor" ~ "2", T2_50 == "Renter" ~ "3")) %>%
  mutate(T2_51 = case_when(T2_51 == "Outright owner" ~ "1", T2_51 == "Mortgagor" ~ "2", T2_51 == "Renter" ~ "3")) %>%
  mutate(T2_52 = case_when(T2_52 == "Outright owner" ~ "1", T2_52 == "Mortgagor" ~ "2", T2_52 == "Renter" ~ "3")) %>%
  mutate(T2_53 = case_when(T2_53 == "Outright owner" ~ "1", T2_53 == "Mortgagor" ~ "2", T2_53 == "Renter" ~ "3")) %>%
  mutate(T2_54 = case_when(T2_54 == "Outright owner" ~ "1", T2_54 == "Mortgagor" ~ "2", T2_54 == "Renter" ~ "3")) %>%
  mutate(T2_55 = case_when(T2_55 == "Outright owner" ~ "1", T2_55 == "Mortgagor" ~ "2", T2_55 == "Renter" ~ "3")) %>%
  mutate(T2_56 = case_when(T2_56 == "Outright owner" ~ "1", T2_56 == "Mortgagor" ~ "2", T2_56 == "Renter" ~ "3")) %>%
  mutate(T2_57 = case_when(T2_57 == "Outright owner" ~ "1", T2_57 == "Mortgagor" ~ "2", T2_57 == "Renter" ~ "3")) %>%
  mutate(T2_58 = case_when(T2_58 == "Outright owner" ~ "1", T2_58 == "Mortgagor" ~ "2", T2_58 == "Renter" ~ "3")) %>%
  mutate(T2_59 = case_when(T2_59 == "Outright owner" ~ "1", T2_59 == "Mortgagor" ~ "2", T2_59 == "Renter" ~ "3")) %>%
  mutate(T2_60 = case_when(T2_60 == "Outright owner" ~ "1", T2_60 == "Mortgagor" ~ "2", T2_60 == "Renter" ~ "3")) %>%
  mutate(T2_61 = case_when(T2_61 == "Outright owner" ~ "1", T2_61 == "Mortgagor" ~ "2", T2_61 == "Renter" ~ "3")) %>%
  mutate(T2_62 = case_when(T2_62 == "Outright owner" ~ "1", T2_62 == "Mortgagor" ~ "2", T2_62 == "Renter" ~ "3")) %>%
  mutate(T2_63 = case_when(T2_63 == "Outright owner" ~ "1", T2_63 == "Mortgagor" ~ "2", T2_63 == "Renter" ~ "3")) %>%
  mutate(T2_64 = case_when(T2_64 == "Outright owner" ~ "1", T2_64 == "Mortgagor" ~ "2", T2_64 == "Renter" ~ "3")) %>%
  mutate(T2_65 = case_when(T2_65 == "Outright owner" ~ "1", T2_65 == "Mortgagor" ~ "2", T2_65 == "Renter" ~ "3"))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~factor(., levels = 0:3)))

# Save start time
start <- Sys.time()

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs", "start")))

# Create containers for results
results_renters <- listenv()
results_outright <- listenv()
results_mortgage <- listenv()

# Set up parallel computing with max 30 cores
workers <- as.numeric(availableCores())
workers <- pmin(45, workers)

plan(multisession, workers = workers)

# Iterate through age range
for (i in c(last_age:51)) {

# Define treatment, outcome, censoring, and confounder variables
treatment <- paste0("T2_", 50:(i - 1))
outcome <- paste0("Y_", 51:i)
censoring <- paste0("C_", 50:(i - 1))
baseline <- c("B1", "B2", "B3", "B4")

vars <- data_wide %>% select(starts_with(c("L"))) %>% names()

time_vary = list()

for (tp in c(50:(i - 1))) {
  time_vary_new <- c(vars[str_detect(vars, str_pad(tp, 2, pad = "0"))])
  
  time_vary[[length(time_vary) + 1]] <- time_vary_new}

  # Initialize TMLE for renters aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "2", "3", "3"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))

  results_renters[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  # Initialize TMLE for outright owners aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "2" | . == "3", "1", "1"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_outright[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}
  
  # Initialize TMLE for mortgagors aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "3", "2", "2"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_mortgage[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  print(paste0("Initialized TMLE for age ", i, "."))

  rm(time_vary_new, tp, shifted)

}

# Gather results
results_renters <- as.list(results_renters)
results_outright <- as.list(results_outright)
results_mortgage <- as.list(results_mortgage)

end <- Sys.time()

print(paste0("Estimation completed at ", paste(hour(end), minute(end), sep = ":"), " after ", round(difftime(end, start, units = "mins"), 0), " minutes."))

rm(treatment, outcome, censoring, time_vary, baseline, workers, i, start, end)

# Clean results
contrasts_outright <- data.frame()
contrasts_mortgage <- data.frame()
results <- data.frame()

for (i in c(51:last_age)) {
  
  cntr <- lmtp_contrast(results_outright[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_outright <- rbind(contrasts_outright, cntr$vals)
  
  cntr <- lmtp_contrast(results_mortgage[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_mortgage <- rbind(contrasts_mortgage, cntr$vals)
  
  rslt <- tidy(results_renters[[i]])
  rslt$age <- i
  rslt$group <- "Renters"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_outright[[i]])
  rslt$age <- i
  rslt$group <- "Outright owners"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_mortgage[[i]])
  rslt$age <- i
  rslt$group <- "Owner w/ mortgage"
  results <- rbind(results, rslt)
  
  rm(cntr, rslt)
  
}

# Covert probability estimate at age 51 into survival
contrasts_outright$age <- c(51:last_age)
contrasts_outright$theta <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$theta, contrasts_outright$theta)
contrasts_outright$conf.low <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.low, contrasts_outright$conf.low)
contrasts_outright$conf.high <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.high, contrasts_outright$conf.high)

contrasts_mortgage$age <- c(51:last_age)
contrasts_mortgage$theta <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$theta, contrasts_mortgage$theta)
contrasts_mortgage$conf.low <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.low, contrasts_mortgage$conf.low)
contrasts_mortgage$conf.high <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.high, contrasts_mortgage$conf.high)

results$estimate <- ifelse(results$age == 51, 1 - results$estimate, results$estimate)
results$conf.low <- ifelse(results$age == 51, 1 - results$conf.low, results$conf.low)
results$conf.high <- ifelse(results$age == 51, 1 - results$conf.high, results$conf.high)

rm(i)

#Save results
save.image("outputs/results_imps2/results_uk_2_imp5.RData")

```

# uk - Imp 6
```{r}

# Load data and choose from imputed data sets
load("data/data_final_uk.RData")

data_wide <- data_uk_imp_wide_6

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs")))

data_wide <- data_wide %>% select(-starts_with(c("T1", "T3")))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~as.character(.)))

data_wide <- data_wide %>%
  mutate(T2_50 = case_when(T2_50 == "Outright owner" ~ "1", T2_50 == "Mortgagor" ~ "2", T2_50 == "Renter" ~ "3")) %>%
  mutate(T2_51 = case_when(T2_51 == "Outright owner" ~ "1", T2_51 == "Mortgagor" ~ "2", T2_51 == "Renter" ~ "3")) %>%
  mutate(T2_52 = case_when(T2_52 == "Outright owner" ~ "1", T2_52 == "Mortgagor" ~ "2", T2_52 == "Renter" ~ "3")) %>%
  mutate(T2_53 = case_when(T2_53 == "Outright owner" ~ "1", T2_53 == "Mortgagor" ~ "2", T2_53 == "Renter" ~ "3")) %>%
  mutate(T2_54 = case_when(T2_54 == "Outright owner" ~ "1", T2_54 == "Mortgagor" ~ "2", T2_54 == "Renter" ~ "3")) %>%
  mutate(T2_55 = case_when(T2_55 == "Outright owner" ~ "1", T2_55 == "Mortgagor" ~ "2", T2_55 == "Renter" ~ "3")) %>%
  mutate(T2_56 = case_when(T2_56 == "Outright owner" ~ "1", T2_56 == "Mortgagor" ~ "2", T2_56 == "Renter" ~ "3")) %>%
  mutate(T2_57 = case_when(T2_57 == "Outright owner" ~ "1", T2_57 == "Mortgagor" ~ "2", T2_57 == "Renter" ~ "3")) %>%
  mutate(T2_58 = case_when(T2_58 == "Outright owner" ~ "1", T2_58 == "Mortgagor" ~ "2", T2_58 == "Renter" ~ "3")) %>%
  mutate(T2_59 = case_when(T2_59 == "Outright owner" ~ "1", T2_59 == "Mortgagor" ~ "2", T2_59 == "Renter" ~ "3")) %>%
  mutate(T2_60 = case_when(T2_60 == "Outright owner" ~ "1", T2_60 == "Mortgagor" ~ "2", T2_60 == "Renter" ~ "3")) %>%
  mutate(T2_61 = case_when(T2_61 == "Outright owner" ~ "1", T2_61 == "Mortgagor" ~ "2", T2_61 == "Renter" ~ "3")) %>%
  mutate(T2_62 = case_when(T2_62 == "Outright owner" ~ "1", T2_62 == "Mortgagor" ~ "2", T2_62 == "Renter" ~ "3")) %>%
  mutate(T2_63 = case_when(T2_63 == "Outright owner" ~ "1", T2_63 == "Mortgagor" ~ "2", T2_63 == "Renter" ~ "3")) %>%
  mutate(T2_64 = case_when(T2_64 == "Outright owner" ~ "1", T2_64 == "Mortgagor" ~ "2", T2_64 == "Renter" ~ "3")) %>%
  mutate(T2_65 = case_when(T2_65 == "Outright owner" ~ "1", T2_65 == "Mortgagor" ~ "2", T2_65 == "Renter" ~ "3"))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~factor(., levels = 0:3)))

# Save start time
start <- Sys.time()

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs", "start")))

# Create containers for results
results_renters <- listenv()
results_outright <- listenv()
results_mortgage <- listenv()

# Set up parallel computing with max 30 cores
workers <- as.numeric(availableCores())
workers <- pmin(45, workers)

plan(multisession, workers = workers)

# Iterate through age range
for (i in c(last_age:51)) {

# Define treatment, outcome, censoring, and confounder variables
treatment <- paste0("T2_", 50:(i - 1))
outcome <- paste0("Y_", 51:i)
censoring <- paste0("C_", 50:(i - 1))
baseline <- c("B1", "B2", "B3", "B4")

vars <- data_wide %>% select(starts_with(c("L"))) %>% names()

time_vary = list()

for (tp in c(50:(i - 1))) {
  time_vary_new <- c(vars[str_detect(vars, str_pad(tp, 2, pad = "0"))])
  
  time_vary[[length(time_vary) + 1]] <- time_vary_new}

  # Initialize TMLE for renters aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "2", "3", "3"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))

  results_renters[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  # Initialize TMLE for outright owners aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "2" | . == "3", "1", "1"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_outright[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}
  
  # Initialize TMLE for mortgagors aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "3", "2", "2"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_mortgage[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  print(paste0("Initialized TMLE for age ", i, "."))

  rm(time_vary_new, tp, shifted)

}

# Gather results
results_renters <- as.list(results_renters)
results_outright <- as.list(results_outright)
results_mortgage <- as.list(results_mortgage)

end <- Sys.time()

print(paste0("Estimation completed at ", paste(hour(end), minute(end), sep = ":"), " after ", round(difftime(end, start, units = "mins"), 0), " minutes."))

rm(treatment, outcome, censoring, time_vary, baseline, workers, i, start, end)

# Clean results
contrasts_outright <- data.frame()
contrasts_mortgage <- data.frame()
results <- data.frame()

for (i in c(51:last_age)) {
  
  cntr <- lmtp_contrast(results_outright[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_outright <- rbind(contrasts_outright, cntr$vals)
  
  cntr <- lmtp_contrast(results_mortgage[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_mortgage <- rbind(contrasts_mortgage, cntr$vals)
  
  rslt <- tidy(results_renters[[i]])
  rslt$age <- i
  rslt$group <- "Renters"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_outright[[i]])
  rslt$age <- i
  rslt$group <- "Outright owners"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_mortgage[[i]])
  rslt$age <- i
  rslt$group <- "Owner w/ mortgage"
  results <- rbind(results, rslt)
  
  rm(cntr, rslt)
  
}

# Covert probability estimate at age 51 into survival
contrasts_outright$age <- c(51:last_age)
contrasts_outright$theta <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$theta, contrasts_outright$theta)
contrasts_outright$conf.low <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.low, contrasts_outright$conf.low)
contrasts_outright$conf.high <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.high, contrasts_outright$conf.high)

contrasts_mortgage$age <- c(51:last_age)
contrasts_mortgage$theta <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$theta, contrasts_mortgage$theta)
contrasts_mortgage$conf.low <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.low, contrasts_mortgage$conf.low)
contrasts_mortgage$conf.high <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.high, contrasts_mortgage$conf.high)

results$estimate <- ifelse(results$age == 51, 1 - results$estimate, results$estimate)
results$conf.low <- ifelse(results$age == 51, 1 - results$conf.low, results$conf.low)
results$conf.high <- ifelse(results$age == 51, 1 - results$conf.high, results$conf.high)

rm(i)

#Save results
save.image("outputs/results_imps2/results_uk_2_imp6.RData")

```

# uk - Imp 7
```{r}

# Load data and choose from imputed data sets
load("data/data_final_uk.RData")

data_wide <- data_uk_imp_wide_7

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs")))

data_wide <- data_wide %>% select(-starts_with(c("T1", "T3")))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~as.character(.)))

data_wide <- data_wide %>%
  mutate(T2_50 = case_when(T2_50 == "Outright owner" ~ "1", T2_50 == "Mortgagor" ~ "2", T2_50 == "Renter" ~ "3")) %>%
  mutate(T2_51 = case_when(T2_51 == "Outright owner" ~ "1", T2_51 == "Mortgagor" ~ "2", T2_51 == "Renter" ~ "3")) %>%
  mutate(T2_52 = case_when(T2_52 == "Outright owner" ~ "1", T2_52 == "Mortgagor" ~ "2", T2_52 == "Renter" ~ "3")) %>%
  mutate(T2_53 = case_when(T2_53 == "Outright owner" ~ "1", T2_53 == "Mortgagor" ~ "2", T2_53 == "Renter" ~ "3")) %>%
  mutate(T2_54 = case_when(T2_54 == "Outright owner" ~ "1", T2_54 == "Mortgagor" ~ "2", T2_54 == "Renter" ~ "3")) %>%
  mutate(T2_55 = case_when(T2_55 == "Outright owner" ~ "1", T2_55 == "Mortgagor" ~ "2", T2_55 == "Renter" ~ "3")) %>%
  mutate(T2_56 = case_when(T2_56 == "Outright owner" ~ "1", T2_56 == "Mortgagor" ~ "2", T2_56 == "Renter" ~ "3")) %>%
  mutate(T2_57 = case_when(T2_57 == "Outright owner" ~ "1", T2_57 == "Mortgagor" ~ "2", T2_57 == "Renter" ~ "3")) %>%
  mutate(T2_58 = case_when(T2_58 == "Outright owner" ~ "1", T2_58 == "Mortgagor" ~ "2", T2_58 == "Renter" ~ "3")) %>%
  mutate(T2_59 = case_when(T2_59 == "Outright owner" ~ "1", T2_59 == "Mortgagor" ~ "2", T2_59 == "Renter" ~ "3")) %>%
  mutate(T2_60 = case_when(T2_60 == "Outright owner" ~ "1", T2_60 == "Mortgagor" ~ "2", T2_60 == "Renter" ~ "3")) %>%
  mutate(T2_61 = case_when(T2_61 == "Outright owner" ~ "1", T2_61 == "Mortgagor" ~ "2", T2_61 == "Renter" ~ "3")) %>%
  mutate(T2_62 = case_when(T2_62 == "Outright owner" ~ "1", T2_62 == "Mortgagor" ~ "2", T2_62 == "Renter" ~ "3")) %>%
  mutate(T2_63 = case_when(T2_63 == "Outright owner" ~ "1", T2_63 == "Mortgagor" ~ "2", T2_63 == "Renter" ~ "3")) %>%
  mutate(T2_64 = case_when(T2_64 == "Outright owner" ~ "1", T2_64 == "Mortgagor" ~ "2", T2_64 == "Renter" ~ "3")) %>%
  mutate(T2_65 = case_when(T2_65 == "Outright owner" ~ "1", T2_65 == "Mortgagor" ~ "2", T2_65 == "Renter" ~ "3"))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~factor(., levels = 0:3)))

# Save start time
start <- Sys.time()

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs", "start")))

# Create containers for results
results_renters <- listenv()
results_outright <- listenv()
results_mortgage <- listenv()

# Set up parallel computing with max 30 cores
workers <- as.numeric(availableCores())
workers <- pmin(45, workers)

plan(multisession, workers = workers)

# Iterate through age range
for (i in c(last_age:51)) {

# Define treatment, outcome, censoring, and confounder variables
treatment <- paste0("T2_", 50:(i - 1))
outcome <- paste0("Y_", 51:i)
censoring <- paste0("C_", 50:(i - 1))
baseline <- c("B1", "B2", "B3", "B4")

vars <- data_wide %>% select(starts_with(c("L"))) %>% names()

time_vary = list()

for (tp in c(50:(i - 1))) {
  time_vary_new <- c(vars[str_detect(vars, str_pad(tp, 2, pad = "0"))])
  
  time_vary[[length(time_vary) + 1]] <- time_vary_new}

  # Initialize TMLE for renters aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "2", "3", "3"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))

  results_renters[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  # Initialize TMLE for outright owners aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "2" | . == "3", "1", "1"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_outright[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}
  
  # Initialize TMLE for mortgagors aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "3", "2", "2"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_mortgage[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  print(paste0("Initialized TMLE for age ", i, "."))

  rm(time_vary_new, tp, shifted)

}

# Gather results
results_renters <- as.list(results_renters)
results_outright <- as.list(results_outright)
results_mortgage <- as.list(results_mortgage)

end <- Sys.time()

print(paste0("Estimation completed at ", paste(hour(end), minute(end), sep = ":"), " after ", round(difftime(end, start, units = "mins"), 0), " minutes."))

rm(treatment, outcome, censoring, time_vary, baseline, workers, i, start, end)

# Clean results
contrasts_outright <- data.frame()
contrasts_mortgage <- data.frame()
results <- data.frame()

for (i in c(51:last_age)) {
  
  cntr <- lmtp_contrast(results_outright[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_outright <- rbind(contrasts_outright, cntr$vals)
  
  cntr <- lmtp_contrast(results_mortgage[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_mortgage <- rbind(contrasts_mortgage, cntr$vals)
  
  rslt <- tidy(results_renters[[i]])
  rslt$age <- i
  rslt$group <- "Renters"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_outright[[i]])
  rslt$age <- i
  rslt$group <- "Outright owners"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_mortgage[[i]])
  rslt$age <- i
  rslt$group <- "Owner w/ mortgage"
  results <- rbind(results, rslt)
  
  rm(cntr, rslt)
  
}

# Covert probability estimate at age 51 into survival
contrasts_outright$age <- c(51:last_age)
contrasts_outright$theta <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$theta, contrasts_outright$theta)
contrasts_outright$conf.low <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.low, contrasts_outright$conf.low)
contrasts_outright$conf.high <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.high, contrasts_outright$conf.high)

contrasts_mortgage$age <- c(51:last_age)
contrasts_mortgage$theta <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$theta, contrasts_mortgage$theta)
contrasts_mortgage$conf.low <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.low, contrasts_mortgage$conf.low)
contrasts_mortgage$conf.high <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.high, contrasts_mortgage$conf.high)

results$estimate <- ifelse(results$age == 51, 1 - results$estimate, results$estimate)
results$conf.low <- ifelse(results$age == 51, 1 - results$conf.low, results$conf.low)
results$conf.high <- ifelse(results$age == 51, 1 - results$conf.high, results$conf.high)

rm(i)

#Save results
save.image("outputs/results_imps2/results_uk_2_imp7.RData")

```

# uk - Imp 8
```{r}

# Load data and choose from imputed data sets
load("data/data_final_uk.RData")

data_wide <- data_uk_imp_wide_8

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs")))

data_wide <- data_wide %>% select(-starts_with(c("T1", "T3")))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~as.character(.)))

data_wide <- data_wide %>%
  mutate(T2_50 = case_when(T2_50 == "Outright owner" ~ "1", T2_50 == "Mortgagor" ~ "2", T2_50 == "Renter" ~ "3")) %>%
  mutate(T2_51 = case_when(T2_51 == "Outright owner" ~ "1", T2_51 == "Mortgagor" ~ "2", T2_51 == "Renter" ~ "3")) %>%
  mutate(T2_52 = case_when(T2_52 == "Outright owner" ~ "1", T2_52 == "Mortgagor" ~ "2", T2_52 == "Renter" ~ "3")) %>%
  mutate(T2_53 = case_when(T2_53 == "Outright owner" ~ "1", T2_53 == "Mortgagor" ~ "2", T2_53 == "Renter" ~ "3")) %>%
  mutate(T2_54 = case_when(T2_54 == "Outright owner" ~ "1", T2_54 == "Mortgagor" ~ "2", T2_54 == "Renter" ~ "3")) %>%
  mutate(T2_55 = case_when(T2_55 == "Outright owner" ~ "1", T2_55 == "Mortgagor" ~ "2", T2_55 == "Renter" ~ "3")) %>%
  mutate(T2_56 = case_when(T2_56 == "Outright owner" ~ "1", T2_56 == "Mortgagor" ~ "2", T2_56 == "Renter" ~ "3")) %>%
  mutate(T2_57 = case_when(T2_57 == "Outright owner" ~ "1", T2_57 == "Mortgagor" ~ "2", T2_57 == "Renter" ~ "3")) %>%
  mutate(T2_58 = case_when(T2_58 == "Outright owner" ~ "1", T2_58 == "Mortgagor" ~ "2", T2_58 == "Renter" ~ "3")) %>%
  mutate(T2_59 = case_when(T2_59 == "Outright owner" ~ "1", T2_59 == "Mortgagor" ~ "2", T2_59 == "Renter" ~ "3")) %>%
  mutate(T2_60 = case_when(T2_60 == "Outright owner" ~ "1", T2_60 == "Mortgagor" ~ "2", T2_60 == "Renter" ~ "3")) %>%
  mutate(T2_61 = case_when(T2_61 == "Outright owner" ~ "1", T2_61 == "Mortgagor" ~ "2", T2_61 == "Renter" ~ "3")) %>%
  mutate(T2_62 = case_when(T2_62 == "Outright owner" ~ "1", T2_62 == "Mortgagor" ~ "2", T2_62 == "Renter" ~ "3")) %>%
  mutate(T2_63 = case_when(T2_63 == "Outright owner" ~ "1", T2_63 == "Mortgagor" ~ "2", T2_63 == "Renter" ~ "3")) %>%
  mutate(T2_64 = case_when(T2_64 == "Outright owner" ~ "1", T2_64 == "Mortgagor" ~ "2", T2_64 == "Renter" ~ "3")) %>%
  mutate(T2_65 = case_when(T2_65 == "Outright owner" ~ "1", T2_65 == "Mortgagor" ~ "2", T2_65 == "Renter" ~ "3"))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~factor(., levels = 0:3)))

# Save start time
start <- Sys.time()

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs", "start")))

# Create containers for results
results_renters <- listenv()
results_outright <- listenv()
results_mortgage <- listenv()

# Set up parallel computing with max 30 cores
workers <- as.numeric(availableCores())
workers <- pmin(45, workers)

plan(multisession, workers = workers)

# Iterate through age range
for (i in c(last_age:51)) {

# Define treatment, outcome, censoring, and confounder variables
treatment <- paste0("T2_", 50:(i - 1))
outcome <- paste0("Y_", 51:i)
censoring <- paste0("C_", 50:(i - 1))
baseline <- c("B1", "B2", "B3", "B4")

vars <- data_wide %>% select(starts_with(c("L"))) %>% names()

time_vary = list()

for (tp in c(50:(i - 1))) {
  time_vary_new <- c(vars[str_detect(vars, str_pad(tp, 2, pad = "0"))])
  
  time_vary[[length(time_vary) + 1]] <- time_vary_new}

  # Initialize TMLE for renters aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "2", "3", "3"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))

  results_renters[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  # Initialize TMLE for outright owners aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "2" | . == "3", "1", "1"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_outright[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}
  
  # Initialize TMLE for mortgagors aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "3", "2", "2"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_mortgage[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  print(paste0("Initialized TMLE for age ", i, "."))

  rm(time_vary_new, tp, shifted)

}

# Gather results
results_renters <- as.list(results_renters)
results_outright <- as.list(results_outright)
results_mortgage <- as.list(results_mortgage)

end <- Sys.time()

print(paste0("Estimation completed at ", paste(hour(end), minute(end), sep = ":"), " after ", round(difftime(end, start, units = "mins"), 0), " minutes."))

rm(treatment, outcome, censoring, time_vary, baseline, workers, i, start, end)

# Clean results
contrasts_outright <- data.frame()
contrasts_mortgage <- data.frame()
results <- data.frame()

for (i in c(51:last_age)) {
  
  cntr <- lmtp_contrast(results_outright[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_outright <- rbind(contrasts_outright, cntr$vals)
  
  cntr <- lmtp_contrast(results_mortgage[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_mortgage <- rbind(contrasts_mortgage, cntr$vals)
  
  rslt <- tidy(results_renters[[i]])
  rslt$age <- i
  rslt$group <- "Renters"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_outright[[i]])
  rslt$age <- i
  rslt$group <- "Outright owners"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_mortgage[[i]])
  rslt$age <- i
  rslt$group <- "Owner w/ mortgage"
  results <- rbind(results, rslt)
  
  rm(cntr, rslt)
  
}

# Covert probability estimate at age 51 into survival
contrasts_outright$age <- c(51:last_age)
contrasts_outright$theta <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$theta, contrasts_outright$theta)
contrasts_outright$conf.low <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.low, contrasts_outright$conf.low)
contrasts_outright$conf.high <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.high, contrasts_outright$conf.high)

contrasts_mortgage$age <- c(51:last_age)
contrasts_mortgage$theta <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$theta, contrasts_mortgage$theta)
contrasts_mortgage$conf.low <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.low, contrasts_mortgage$conf.low)
contrasts_mortgage$conf.high <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.high, contrasts_mortgage$conf.high)

results$estimate <- ifelse(results$age == 51, 1 - results$estimate, results$estimate)
results$conf.low <- ifelse(results$age == 51, 1 - results$conf.low, results$conf.low)
results$conf.high <- ifelse(results$age == 51, 1 - results$conf.high, results$conf.high)

rm(i)

#Save results
save.image("outputs/results_imps2/results_uk_2_imp8.RData")

```

# uk - Imp 9
```{r}

# Load data and choose from imputed data sets
load("data/data_final_uk.RData")

data_wide <- data_uk_imp_wide_9

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs")))

data_wide <- data_wide %>% select(-starts_with(c("T1", "T3")))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~as.character(.)))

data_wide <- data_wide %>%
  mutate(T2_50 = case_when(T2_50 == "Outright owner" ~ "1", T2_50 == "Mortgagor" ~ "2", T2_50 == "Renter" ~ "3")) %>%
  mutate(T2_51 = case_when(T2_51 == "Outright owner" ~ "1", T2_51 == "Mortgagor" ~ "2", T2_51 == "Renter" ~ "3")) %>%
  mutate(T2_52 = case_when(T2_52 == "Outright owner" ~ "1", T2_52 == "Mortgagor" ~ "2", T2_52 == "Renter" ~ "3")) %>%
  mutate(T2_53 = case_when(T2_53 == "Outright owner" ~ "1", T2_53 == "Mortgagor" ~ "2", T2_53 == "Renter" ~ "3")) %>%
  mutate(T2_54 = case_when(T2_54 == "Outright owner" ~ "1", T2_54 == "Mortgagor" ~ "2", T2_54 == "Renter" ~ "3")) %>%
  mutate(T2_55 = case_when(T2_55 == "Outright owner" ~ "1", T2_55 == "Mortgagor" ~ "2", T2_55 == "Renter" ~ "3")) %>%
  mutate(T2_56 = case_when(T2_56 == "Outright owner" ~ "1", T2_56 == "Mortgagor" ~ "2", T2_56 == "Renter" ~ "3")) %>%
  mutate(T2_57 = case_when(T2_57 == "Outright owner" ~ "1", T2_57 == "Mortgagor" ~ "2", T2_57 == "Renter" ~ "3")) %>%
  mutate(T2_58 = case_when(T2_58 == "Outright owner" ~ "1", T2_58 == "Mortgagor" ~ "2", T2_58 == "Renter" ~ "3")) %>%
  mutate(T2_59 = case_when(T2_59 == "Outright owner" ~ "1", T2_59 == "Mortgagor" ~ "2", T2_59 == "Renter" ~ "3")) %>%
  mutate(T2_60 = case_when(T2_60 == "Outright owner" ~ "1", T2_60 == "Mortgagor" ~ "2", T2_60 == "Renter" ~ "3")) %>%
  mutate(T2_61 = case_when(T2_61 == "Outright owner" ~ "1", T2_61 == "Mortgagor" ~ "2", T2_61 == "Renter" ~ "3")) %>%
  mutate(T2_62 = case_when(T2_62 == "Outright owner" ~ "1", T2_62 == "Mortgagor" ~ "2", T2_62 == "Renter" ~ "3")) %>%
  mutate(T2_63 = case_when(T2_63 == "Outright owner" ~ "1", T2_63 == "Mortgagor" ~ "2", T2_63 == "Renter" ~ "3")) %>%
  mutate(T2_64 = case_when(T2_64 == "Outright owner" ~ "1", T2_64 == "Mortgagor" ~ "2", T2_64 == "Renter" ~ "3")) %>%
  mutate(T2_65 = case_when(T2_65 == "Outright owner" ~ "1", T2_65 == "Mortgagor" ~ "2", T2_65 == "Renter" ~ "3"))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~factor(., levels = 0:3)))

# Save start time
start <- Sys.time()

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs", "start")))

# Create containers for results
results_renters <- listenv()
results_outright <- listenv()
results_mortgage <- listenv()

# Set up parallel computing with max 30 cores
workers <- as.numeric(availableCores())
workers <- pmin(45, workers)

plan(multisession, workers = workers)

# Iterate through age range
for (i in c(last_age:51)) {

# Define treatment, outcome, censoring, and confounder variables
treatment <- paste0("T2_", 50:(i - 1))
outcome <- paste0("Y_", 51:i)
censoring <- paste0("C_", 50:(i - 1))
baseline <- c("B1", "B2", "B3", "B4")

vars <- data_wide %>% select(starts_with(c("L"))) %>% names()

time_vary = list()

for (tp in c(50:(i - 1))) {
  time_vary_new <- c(vars[str_detect(vars, str_pad(tp, 2, pad = "0"))])
  
  time_vary[[length(time_vary) + 1]] <- time_vary_new}

  # Initialize TMLE for renters aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "2", "3", "3"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))

  results_renters[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  # Initialize TMLE for outright owners aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "2" | . == "3", "1", "1"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_outright[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}
  
  # Initialize TMLE for mortgagors aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "3", "2", "2"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_mortgage[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  print(paste0("Initialized TMLE for age ", i, "."))

  rm(time_vary_new, tp, shifted)

}

# Gather results
results_renters <- as.list(results_renters)
results_outright <- as.list(results_outright)
results_mortgage <- as.list(results_mortgage)

end <- Sys.time()

print(paste0("Estimation completed at ", paste(hour(end), minute(end), sep = ":"), " after ", round(difftime(end, start, units = "mins"), 0), " minutes."))

rm(treatment, outcome, censoring, time_vary, baseline, workers, i, start, end)

# Clean results
contrasts_outright <- data.frame()
contrasts_mortgage <- data.frame()
results <- data.frame()

for (i in c(51:last_age)) {
  
  cntr <- lmtp_contrast(results_outright[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_outright <- rbind(contrasts_outright, cntr$vals)
  
  cntr <- lmtp_contrast(results_mortgage[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_mortgage <- rbind(contrasts_mortgage, cntr$vals)
  
  rslt <- tidy(results_renters[[i]])
  rslt$age <- i
  rslt$group <- "Renters"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_outright[[i]])
  rslt$age <- i
  rslt$group <- "Outright owners"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_mortgage[[i]])
  rslt$age <- i
  rslt$group <- "Owner w/ mortgage"
  results <- rbind(results, rslt)
  
  rm(cntr, rslt)
  
}

# Covert probability estimate at age 51 into survival
contrasts_outright$age <- c(51:last_age)
contrasts_outright$theta <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$theta, contrasts_outright$theta)
contrasts_outright$conf.low <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.low, contrasts_outright$conf.low)
contrasts_outright$conf.high <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.high, contrasts_outright$conf.high)

contrasts_mortgage$age <- c(51:last_age)
contrasts_mortgage$theta <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$theta, contrasts_mortgage$theta)
contrasts_mortgage$conf.low <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.low, contrasts_mortgage$conf.low)
contrasts_mortgage$conf.high <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.high, contrasts_mortgage$conf.high)

results$estimate <- ifelse(results$age == 51, 1 - results$estimate, results$estimate)
results$conf.low <- ifelse(results$age == 51, 1 - results$conf.low, results$conf.low)
results$conf.high <- ifelse(results$age == 51, 1 - results$conf.high, results$conf.high)

rm(i)

#Save results
save.image("outputs/results_imps2/results_uk_2_imp9.RData")

```

# uk - Imp 10
```{r}

# Load data and choose from imputed data sets
load("data/data_final_uk.RData")

data_wide <- data_uk_imp_wide_10

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs")))

data_wide <- data_wide %>% select(-starts_with(c("T1", "T3")))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~as.character(.)))

data_wide <- data_wide %>%
  mutate(T2_50 = case_when(T2_50 == "Outright owner" ~ "1", T2_50 == "Mortgagor" ~ "2", T2_50 == "Renter" ~ "3")) %>%
  mutate(T2_51 = case_when(T2_51 == "Outright owner" ~ "1", T2_51 == "Mortgagor" ~ "2", T2_51 == "Renter" ~ "3")) %>%
  mutate(T2_52 = case_when(T2_52 == "Outright owner" ~ "1", T2_52 == "Mortgagor" ~ "2", T2_52 == "Renter" ~ "3")) %>%
  mutate(T2_53 = case_when(T2_53 == "Outright owner" ~ "1", T2_53 == "Mortgagor" ~ "2", T2_53 == "Renter" ~ "3")) %>%
  mutate(T2_54 = case_when(T2_54 == "Outright owner" ~ "1", T2_54 == "Mortgagor" ~ "2", T2_54 == "Renter" ~ "3")) %>%
  mutate(T2_55 = case_when(T2_55 == "Outright owner" ~ "1", T2_55 == "Mortgagor" ~ "2", T2_55 == "Renter" ~ "3")) %>%
  mutate(T2_56 = case_when(T2_56 == "Outright owner" ~ "1", T2_56 == "Mortgagor" ~ "2", T2_56 == "Renter" ~ "3")) %>%
  mutate(T2_57 = case_when(T2_57 == "Outright owner" ~ "1", T2_57 == "Mortgagor" ~ "2", T2_57 == "Renter" ~ "3")) %>%
  mutate(T2_58 = case_when(T2_58 == "Outright owner" ~ "1", T2_58 == "Mortgagor" ~ "2", T2_58 == "Renter" ~ "3")) %>%
  mutate(T2_59 = case_when(T2_59 == "Outright owner" ~ "1", T2_59 == "Mortgagor" ~ "2", T2_59 == "Renter" ~ "3")) %>%
  mutate(T2_60 = case_when(T2_60 == "Outright owner" ~ "1", T2_60 == "Mortgagor" ~ "2", T2_60 == "Renter" ~ "3")) %>%
  mutate(T2_61 = case_when(T2_61 == "Outright owner" ~ "1", T2_61 == "Mortgagor" ~ "2", T2_61 == "Renter" ~ "3")) %>%
  mutate(T2_62 = case_when(T2_62 == "Outright owner" ~ "1", T2_62 == "Mortgagor" ~ "2", T2_62 == "Renter" ~ "3")) %>%
  mutate(T2_63 = case_when(T2_63 == "Outright owner" ~ "1", T2_63 == "Mortgagor" ~ "2", T2_63 == "Renter" ~ "3")) %>%
  mutate(T2_64 = case_when(T2_64 == "Outright owner" ~ "1", T2_64 == "Mortgagor" ~ "2", T2_64 == "Renter" ~ "3")) %>%
  mutate(T2_65 = case_when(T2_65 == "Outright owner" ~ "1", T2_65 == "Mortgagor" ~ "2", T2_65 == "Renter" ~ "3"))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~factor(., levels = 0:3)))

# Save start time
start <- Sys.time()

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs", "start")))

# Create containers for results
results_renters <- listenv()
results_outright <- listenv()
results_mortgage <- listenv()

# Set up parallel computing with max 30 cores
workers <- as.numeric(availableCores())
workers <- pmin(45, workers)

plan(multisession, workers = workers)

# Iterate through age range
for (i in c(last_age:51)) {

# Define treatment, outcome, censoring, and confounder variables
treatment <- paste0("T2_", 50:(i - 1))
outcome <- paste0("Y_", 51:i)
censoring <- paste0("C_", 50:(i - 1))
baseline <- c("B1", "B2", "B3", "B4")

vars <- data_wide %>% select(starts_with(c("L"))) %>% names()

time_vary = list()

for (tp in c(50:(i - 1))) {
  time_vary_new <- c(vars[str_detect(vars, str_pad(tp, 2, pad = "0"))])
  
  time_vary[[length(time_vary) + 1]] <- time_vary_new}

  # Initialize TMLE for renters aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "2", "3", "3"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))

  results_renters[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  # Initialize TMLE for outright owners aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "2" | . == "3", "1", "1"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_outright[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}
  
  # Initialize TMLE for mortgagors aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "3", "2", "2"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_mortgage[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  print(paste0("Initialized TMLE for age ", i, "."))

  rm(time_vary_new, tp, shifted)

}

# Gather results
results_renters <- as.list(results_renters)
results_outright <- as.list(results_outright)
results_mortgage <- as.list(results_mortgage)

end <- Sys.time()

print(paste0("Estimation completed at ", paste(hour(end), minute(end), sep = ":"), " after ", round(difftime(end, start, units = "mins"), 0), " minutes."))

rm(treatment, outcome, censoring, time_vary, baseline, workers, i, start, end)

# Clean results
contrasts_outright <- data.frame()
contrasts_mortgage <- data.frame()
results <- data.frame()

for (i in c(51:last_age)) {
  
  cntr <- lmtp_contrast(results_outright[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_outright <- rbind(contrasts_outright, cntr$vals)
  
  cntr <- lmtp_contrast(results_mortgage[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_mortgage <- rbind(contrasts_mortgage, cntr$vals)
  
  rslt <- tidy(results_renters[[i]])
  rslt$age <- i
  rslt$group <- "Renters"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_outright[[i]])
  rslt$age <- i
  rslt$group <- "Outright owners"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_mortgage[[i]])
  rslt$age <- i
  rslt$group <- "Owner w/ mortgage"
  results <- rbind(results, rslt)
  
  rm(cntr, rslt)
  
}

# Covert probability estimate at age 51 into survival
contrasts_outright$age <- c(51:last_age)
contrasts_outright$theta <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$theta, contrasts_outright$theta)
contrasts_outright$conf.low <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.low, contrasts_outright$conf.low)
contrasts_outright$conf.high <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.high, contrasts_outright$conf.high)

contrasts_mortgage$age <- c(51:last_age)
contrasts_mortgage$theta <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$theta, contrasts_mortgage$theta)
contrasts_mortgage$conf.low <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.low, contrasts_mortgage$conf.low)
contrasts_mortgage$conf.high <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.high, contrasts_mortgage$conf.high)

results$estimate <- ifelse(results$age == 51, 1 - results$estimate, results$estimate)
results$conf.low <- ifelse(results$age == 51, 1 - results$conf.low, results$conf.low)
results$conf.high <- ifelse(results$age == 51, 1 - results$conf.high, results$conf.high)

rm(i)

#Save results
save.image("outputs/results_imps2/results_uk_2_imp10.RData")

```

# de - Imp 1
```{r}

# Load data and choose from imputed data sets
load("data/data_final_de.RData")

data_wide <- data_de_imp_wide_1

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs")))

data_wide <- data_wide %>% select(-starts_with(c("T1", "T3")))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~as.character(.)))

data_wide <- data_wide %>%
  mutate(T2_50 = case_when(T2_50 == "Outright owner" ~ "1", T2_50 == "Mortgagor" ~ "2", T2_50 == "Renter" ~ "3")) %>%
  mutate(T2_51 = case_when(T2_51 == "Outright owner" ~ "1", T2_51 == "Mortgagor" ~ "2", T2_51 == "Renter" ~ "3")) %>%
  mutate(T2_52 = case_when(T2_52 == "Outright owner" ~ "1", T2_52 == "Mortgagor" ~ "2", T2_52 == "Renter" ~ "3")) %>%
  mutate(T2_53 = case_when(T2_53 == "Outright owner" ~ "1", T2_53 == "Mortgagor" ~ "2", T2_53 == "Renter" ~ "3")) %>%
  mutate(T2_54 = case_when(T2_54 == "Outright owner" ~ "1", T2_54 == "Mortgagor" ~ "2", T2_54 == "Renter" ~ "3")) %>%
  mutate(T2_55 = case_when(T2_55 == "Outright owner" ~ "1", T2_55 == "Mortgagor" ~ "2", T2_55 == "Renter" ~ "3")) %>%
  mutate(T2_56 = case_when(T2_56 == "Outright owner" ~ "1", T2_56 == "Mortgagor" ~ "2", T2_56 == "Renter" ~ "3")) %>%
  mutate(T2_57 = case_when(T2_57 == "Outright owner" ~ "1", T2_57 == "Mortgagor" ~ "2", T2_57 == "Renter" ~ "3")) %>%
  mutate(T2_58 = case_when(T2_58 == "Outright owner" ~ "1", T2_58 == "Mortgagor" ~ "2", T2_58 == "Renter" ~ "3")) %>%
  mutate(T2_59 = case_when(T2_59 == "Outright owner" ~ "1", T2_59 == "Mortgagor" ~ "2", T2_59 == "Renter" ~ "3")) %>%
  mutate(T2_60 = case_when(T2_60 == "Outright owner" ~ "1", T2_60 == "Mortgagor" ~ "2", T2_60 == "Renter" ~ "3")) %>%
  mutate(T2_61 = case_when(T2_61 == "Outright owner" ~ "1", T2_61 == "Mortgagor" ~ "2", T2_61 == "Renter" ~ "3")) %>%
  mutate(T2_62 = case_when(T2_62 == "Outright owner" ~ "1", T2_62 == "Mortgagor" ~ "2", T2_62 == "Renter" ~ "3")) %>%
  mutate(T2_63 = case_when(T2_63 == "Outright owner" ~ "1", T2_63 == "Mortgagor" ~ "2", T2_63 == "Renter" ~ "3")) %>%
  mutate(T2_64 = case_when(T2_64 == "Outright owner" ~ "1", T2_64 == "Mortgagor" ~ "2", T2_64 == "Renter" ~ "3")) %>%
  mutate(T2_65 = case_when(T2_65 == "Outright owner" ~ "1", T2_65 == "Mortgagor" ~ "2", T2_65 == "Renter" ~ "3"))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~factor(., levels = 0:3)))

# Save start time
start <- Sys.time()

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs", "start")))

# Create containers for results
results_renters <- listenv()
results_outright <- listenv()
results_mortgage <- listenv()

# Set up parallel computing with max 30 cores
workers <- as.numeric(availableCores())
workers <- pmin(45, workers)

plan(multisession, workers = workers)

# Iterate through age range
for (i in c(last_age:51)) {

# Define treatment, outcome, censoring, and confounder variables
treatment <- paste0("T2_", 50:(i - 1))
outcome <- paste0("Y_", 51:i)
censoring <- paste0("C_", 50:(i - 1))
baseline <- c("B1", "B2", "B3", "B4")

vars <- data_wide %>% select(starts_with(c("L"))) %>% names()

time_vary = list()

for (tp in c(50:(i - 1))) {
  time_vary_new <- c(vars[str_detect(vars, str_pad(tp, 2, pad = "0"))])
  
  time_vary[[length(time_vary) + 1]] <- time_vary_new}

  # Initialize TMLE for renters aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "2", "3", "3"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))

  results_renters[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  # Initialize TMLE for outright owners aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "2" | . == "3", "1", "1"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_outright[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}
  
  # Initialize TMLE for mortgagors aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "3", "2", "2"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_mortgage[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  print(paste0("Initialized TMLE for age ", i, "."))

  rm(time_vary_new, tp, shifted)

}

# Gather results
results_renters <- as.list(results_renters)
results_outright <- as.list(results_outright)
results_mortgage <- as.list(results_mortgage)

end <- Sys.time()

print(paste0("Estimation completed at ", paste(hour(end), minute(end), sep = ":"), " after ", round(difftime(end, start, units = "mins"), 0), " minutes."))

rm(treatment, outcome, censoring, time_vary, baseline, workers, i, start, end)

# Clean results
contrasts_outright <- data.frame()
contrasts_mortgage <- data.frame()
results <- data.frame()

for (i in c(51:last_age)) {
  
  cntr <- lmtp_contrast(results_outright[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_outright <- rbind(contrasts_outright, cntr$vals)
  
  cntr <- lmtp_contrast(results_mortgage[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_mortgage <- rbind(contrasts_mortgage, cntr$vals)
  
  rslt <- tidy(results_renters[[i]])
  rslt$age <- i
  rslt$group <- "Renters"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_outright[[i]])
  rslt$age <- i
  rslt$group <- "Outright owners"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_mortgage[[i]])
  rslt$age <- i
  rslt$group <- "Owner w/ mortgage"
  results <- rbind(results, rslt)
  
  rm(cntr, rslt)
  
}

# Covert probability estimate at age 51 into survival
contrasts_outright$age <- c(51:last_age)
contrasts_outright$theta <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$theta, contrasts_outright$theta)
contrasts_outright$conf.low <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.low, contrasts_outright$conf.low)
contrasts_outright$conf.high <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.high, contrasts_outright$conf.high)

contrasts_mortgage$age <- c(51:last_age)
contrasts_mortgage$theta <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$theta, contrasts_mortgage$theta)
contrasts_mortgage$conf.low <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.low, contrasts_mortgage$conf.low)
contrasts_mortgage$conf.high <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.high, contrasts_mortgage$conf.high)

results$estimate <- ifelse(results$age == 51, 1 - results$estimate, results$estimate)
results$conf.low <- ifelse(results$age == 51, 1 - results$conf.low, results$conf.low)
results$conf.high <- ifelse(results$age == 51, 1 - results$conf.high, results$conf.high)

rm(i)

#Save results
save.image("outputs/results_imps2/results_de_2_imp1.RData")

```

# de - Imp 2
```{r}

# Load data and choose from imputed data sets
load("data/data_final_de.RData")

data_wide <- data_de_imp_wide_2

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs")))

data_wide <- data_wide %>% select(-starts_with(c("T1", "T3")))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~as.character(.)))

data_wide <- data_wide %>%
  mutate(T2_50 = case_when(T2_50 == "Outright owner" ~ "1", T2_50 == "Mortgagor" ~ "2", T2_50 == "Renter" ~ "3")) %>%
  mutate(T2_51 = case_when(T2_51 == "Outright owner" ~ "1", T2_51 == "Mortgagor" ~ "2", T2_51 == "Renter" ~ "3")) %>%
  mutate(T2_52 = case_when(T2_52 == "Outright owner" ~ "1", T2_52 == "Mortgagor" ~ "2", T2_52 == "Renter" ~ "3")) %>%
  mutate(T2_53 = case_when(T2_53 == "Outright owner" ~ "1", T2_53 == "Mortgagor" ~ "2", T2_53 == "Renter" ~ "3")) %>%
  mutate(T2_54 = case_when(T2_54 == "Outright owner" ~ "1", T2_54 == "Mortgagor" ~ "2", T2_54 == "Renter" ~ "3")) %>%
  mutate(T2_55 = case_when(T2_55 == "Outright owner" ~ "1", T2_55 == "Mortgagor" ~ "2", T2_55 == "Renter" ~ "3")) %>%
  mutate(T2_56 = case_when(T2_56 == "Outright owner" ~ "1", T2_56 == "Mortgagor" ~ "2", T2_56 == "Renter" ~ "3")) %>%
  mutate(T2_57 = case_when(T2_57 == "Outright owner" ~ "1", T2_57 == "Mortgagor" ~ "2", T2_57 == "Renter" ~ "3")) %>%
  mutate(T2_58 = case_when(T2_58 == "Outright owner" ~ "1", T2_58 == "Mortgagor" ~ "2", T2_58 == "Renter" ~ "3")) %>%
  mutate(T2_59 = case_when(T2_59 == "Outright owner" ~ "1", T2_59 == "Mortgagor" ~ "2", T2_59 == "Renter" ~ "3")) %>%
  mutate(T2_60 = case_when(T2_60 == "Outright owner" ~ "1", T2_60 == "Mortgagor" ~ "2", T2_60 == "Renter" ~ "3")) %>%
  mutate(T2_61 = case_when(T2_61 == "Outright owner" ~ "1", T2_61 == "Mortgagor" ~ "2", T2_61 == "Renter" ~ "3")) %>%
  mutate(T2_62 = case_when(T2_62 == "Outright owner" ~ "1", T2_62 == "Mortgagor" ~ "2", T2_62 == "Renter" ~ "3")) %>%
  mutate(T2_63 = case_when(T2_63 == "Outright owner" ~ "1", T2_63 == "Mortgagor" ~ "2", T2_63 == "Renter" ~ "3")) %>%
  mutate(T2_64 = case_when(T2_64 == "Outright owner" ~ "1", T2_64 == "Mortgagor" ~ "2", T2_64 == "Renter" ~ "3")) %>%
  mutate(T2_65 = case_when(T2_65 == "Outright owner" ~ "1", T2_65 == "Mortgagor" ~ "2", T2_65 == "Renter" ~ "3"))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~factor(., levels = 0:3)))

# Save start time
start <- Sys.time()

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs", "start")))

# Create containers for results
results_renters <- listenv()
results_outright <- listenv()
results_mortgage <- listenv()

# Set up parallel computing with max 30 cores
workers <- as.numeric(availableCores())
workers <- pmin(45, workers)

plan(multisession, workers = workers)

# Iterate through age range
for (i in c(last_age:51)) {

# Define treatment, outcome, censoring, and confounder variables
treatment <- paste0("T2_", 50:(i - 1))
outcome <- paste0("Y_", 51:i)
censoring <- paste0("C_", 50:(i - 1))
baseline <- c("B1", "B2", "B3", "B4")

vars <- data_wide %>% select(starts_with(c("L"))) %>% names()

time_vary = list()

for (tp in c(50:(i - 1))) {
  time_vary_new <- c(vars[str_detect(vars, str_pad(tp, 2, pad = "0"))])
  
  time_vary[[length(time_vary) + 1]] <- time_vary_new}

  # Initialize TMLE for renters aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "2", "3", "3"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))

  results_renters[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  # Initialize TMLE for outright owners aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "2" | . == "3", "1", "1"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_outright[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}
  
  # Initialize TMLE for mortgagors aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "3", "2", "2"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_mortgage[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  print(paste0("Initialized TMLE for age ", i, "."))

  rm(time_vary_new, tp, shifted)

}

# Gather results
results_renters <- as.list(results_renters)
results_outright <- as.list(results_outright)
results_mortgage <- as.list(results_mortgage)

end <- Sys.time()

print(paste0("Estimation completed at ", paste(hour(end), minute(end), sep = ":"), " after ", round(difftime(end, start, units = "mins"), 0), " minutes."))

rm(treatment, outcome, censoring, time_vary, baseline, workers, i, start, end)

# Clean results
contrasts_outright <- data.frame()
contrasts_mortgage <- data.frame()
results <- data.frame()

for (i in c(51:last_age)) {
  
  cntr <- lmtp_contrast(results_outright[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_outright <- rbind(contrasts_outright, cntr$vals)
  
  cntr <- lmtp_contrast(results_mortgage[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_mortgage <- rbind(contrasts_mortgage, cntr$vals)
  
  rslt <- tidy(results_renters[[i]])
  rslt$age <- i
  rslt$group <- "Renters"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_outright[[i]])
  rslt$age <- i
  rslt$group <- "Outright owners"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_mortgage[[i]])
  rslt$age <- i
  rslt$group <- "Owner w/ mortgage"
  results <- rbind(results, rslt)
  
  rm(cntr, rslt)
  
}

# Covert probability estimate at age 51 into survival
contrasts_outright$age <- c(51:last_age)
contrasts_outright$theta <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$theta, contrasts_outright$theta)
contrasts_outright$conf.low <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.low, contrasts_outright$conf.low)
contrasts_outright$conf.high <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.high, contrasts_outright$conf.high)

contrasts_mortgage$age <- c(51:last_age)
contrasts_mortgage$theta <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$theta, contrasts_mortgage$theta)
contrasts_mortgage$conf.low <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.low, contrasts_mortgage$conf.low)
contrasts_mortgage$conf.high <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.high, contrasts_mortgage$conf.high)

results$estimate <- ifelse(results$age == 51, 1 - results$estimate, results$estimate)
results$conf.low <- ifelse(results$age == 51, 1 - results$conf.low, results$conf.low)
results$conf.high <- ifelse(results$age == 51, 1 - results$conf.high, results$conf.high)

rm(i)

#Save results
save.image("outputs/results_imps2/results_de_2_imp2.RData")

```

# de - Imp 3
```{r}

# Load data and choose from imputed data sets
load("data/data_final_de.RData")

data_wide <- data_de_imp_wide_3

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs")))

data_wide <- data_wide %>% select(-starts_with(c("T1", "T3")))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~as.character(.)))

data_wide <- data_wide %>%
  mutate(T2_50 = case_when(T2_50 == "Outright owner" ~ "1", T2_50 == "Mortgagor" ~ "2", T2_50 == "Renter" ~ "3")) %>%
  mutate(T2_51 = case_when(T2_51 == "Outright owner" ~ "1", T2_51 == "Mortgagor" ~ "2", T2_51 == "Renter" ~ "3")) %>%
  mutate(T2_52 = case_when(T2_52 == "Outright owner" ~ "1", T2_52 == "Mortgagor" ~ "2", T2_52 == "Renter" ~ "3")) %>%
  mutate(T2_53 = case_when(T2_53 == "Outright owner" ~ "1", T2_53 == "Mortgagor" ~ "2", T2_53 == "Renter" ~ "3")) %>%
  mutate(T2_54 = case_when(T2_54 == "Outright owner" ~ "1", T2_54 == "Mortgagor" ~ "2", T2_54 == "Renter" ~ "3")) %>%
  mutate(T2_55 = case_when(T2_55 == "Outright owner" ~ "1", T2_55 == "Mortgagor" ~ "2", T2_55 == "Renter" ~ "3")) %>%
  mutate(T2_56 = case_when(T2_56 == "Outright owner" ~ "1", T2_56 == "Mortgagor" ~ "2", T2_56 == "Renter" ~ "3")) %>%
  mutate(T2_57 = case_when(T2_57 == "Outright owner" ~ "1", T2_57 == "Mortgagor" ~ "2", T2_57 == "Renter" ~ "3")) %>%
  mutate(T2_58 = case_when(T2_58 == "Outright owner" ~ "1", T2_58 == "Mortgagor" ~ "2", T2_58 == "Renter" ~ "3")) %>%
  mutate(T2_59 = case_when(T2_59 == "Outright owner" ~ "1", T2_59 == "Mortgagor" ~ "2", T2_59 == "Renter" ~ "3")) %>%
  mutate(T2_60 = case_when(T2_60 == "Outright owner" ~ "1", T2_60 == "Mortgagor" ~ "2", T2_60 == "Renter" ~ "3")) %>%
  mutate(T2_61 = case_when(T2_61 == "Outright owner" ~ "1", T2_61 == "Mortgagor" ~ "2", T2_61 == "Renter" ~ "3")) %>%
  mutate(T2_62 = case_when(T2_62 == "Outright owner" ~ "1", T2_62 == "Mortgagor" ~ "2", T2_62 == "Renter" ~ "3")) %>%
  mutate(T2_63 = case_when(T2_63 == "Outright owner" ~ "1", T2_63 == "Mortgagor" ~ "2", T2_63 == "Renter" ~ "3")) %>%
  mutate(T2_64 = case_when(T2_64 == "Outright owner" ~ "1", T2_64 == "Mortgagor" ~ "2", T2_64 == "Renter" ~ "3")) %>%
  mutate(T2_65 = case_when(T2_65 == "Outright owner" ~ "1", T2_65 == "Mortgagor" ~ "2", T2_65 == "Renter" ~ "3"))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~factor(., levels = 0:3)))

# Save start time
start <- Sys.time()

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs", "start")))

# Create containers for results
results_renters <- listenv()
results_outright <- listenv()
results_mortgage <- listenv()

# Set up parallel computing with max 30 cores
workers <- as.numeric(availableCores())
workers <- pmin(45, workers)

plan(multisession, workers = workers)

# Iterate through age range
for (i in c(last_age:51)) {

# Define treatment, outcome, censoring, and confounder variables
treatment <- paste0("T2_", 50:(i - 1))
outcome <- paste0("Y_", 51:i)
censoring <- paste0("C_", 50:(i - 1))
baseline <- c("B1", "B2", "B3", "B4")

vars <- data_wide %>% select(starts_with(c("L"))) %>% names()

time_vary = list()

for (tp in c(50:(i - 1))) {
  time_vary_new <- c(vars[str_detect(vars, str_pad(tp, 2, pad = "0"))])
  
  time_vary[[length(time_vary) + 1]] <- time_vary_new}

  # Initialize TMLE for renters aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "2", "3", "3"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))

  results_renters[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  # Initialize TMLE for outright owners aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "2" | . == "3", "1", "1"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_outright[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}
  
  # Initialize TMLE for mortgagors aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "3", "2", "2"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_mortgage[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  print(paste0("Initialized TMLE for age ", i, "."))

  rm(time_vary_new, tp, shifted)

}

# Gather results
results_renters <- as.list(results_renters)
results_outright <- as.list(results_outright)
results_mortgage <- as.list(results_mortgage)

end <- Sys.time()

print(paste0("Estimation completed at ", paste(hour(end), minute(end), sep = ":"), " after ", round(difftime(end, start, units = "mins"), 0), " minutes."))

rm(treatment, outcome, censoring, time_vary, baseline, workers, i, start, end)

# Clean results
contrasts_outright <- data.frame()
contrasts_mortgage <- data.frame()
results <- data.frame()

for (i in c(51:last_age)) {
  
  cntr <- lmtp_contrast(results_outright[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_outright <- rbind(contrasts_outright, cntr$vals)
  
  cntr <- lmtp_contrast(results_mortgage[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_mortgage <- rbind(contrasts_mortgage, cntr$vals)
  
  rslt <- tidy(results_renters[[i]])
  rslt$age <- i
  rslt$group <- "Renters"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_outright[[i]])
  rslt$age <- i
  rslt$group <- "Outright owners"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_mortgage[[i]])
  rslt$age <- i
  rslt$group <- "Owner w/ mortgage"
  results <- rbind(results, rslt)
  
  rm(cntr, rslt)
  
}

# Covert probability estimate at age 51 into survival
contrasts_outright$age <- c(51:last_age)
contrasts_outright$theta <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$theta, contrasts_outright$theta)
contrasts_outright$conf.low <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.low, contrasts_outright$conf.low)
contrasts_outright$conf.high <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.high, contrasts_outright$conf.high)

contrasts_mortgage$age <- c(51:last_age)
contrasts_mortgage$theta <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$theta, contrasts_mortgage$theta)
contrasts_mortgage$conf.low <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.low, contrasts_mortgage$conf.low)
contrasts_mortgage$conf.high <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.high, contrasts_mortgage$conf.high)

results$estimate <- ifelse(results$age == 51, 1 - results$estimate, results$estimate)
results$conf.low <- ifelse(results$age == 51, 1 - results$conf.low, results$conf.low)
results$conf.high <- ifelse(results$age == 51, 1 - results$conf.high, results$conf.high)

rm(i)

#Save results
save.image("outputs/results_imps2/results_de_2_imp3.RData")

```

# de - Imp 4
```{r}

# Load data and choose from imputed data sets
load("data/data_final_de.RData")

data_wide <- data_de_imp_wide_4

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs")))

data_wide <- data_wide %>% select(-starts_with(c("T1", "T3")))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~as.character(.)))

data_wide <- data_wide %>%
  mutate(T2_50 = case_when(T2_50 == "Outright owner" ~ "1", T2_50 == "Mortgagor" ~ "2", T2_50 == "Renter" ~ "3")) %>%
  mutate(T2_51 = case_when(T2_51 == "Outright owner" ~ "1", T2_51 == "Mortgagor" ~ "2", T2_51 == "Renter" ~ "3")) %>%
  mutate(T2_52 = case_when(T2_52 == "Outright owner" ~ "1", T2_52 == "Mortgagor" ~ "2", T2_52 == "Renter" ~ "3")) %>%
  mutate(T2_53 = case_when(T2_53 == "Outright owner" ~ "1", T2_53 == "Mortgagor" ~ "2", T2_53 == "Renter" ~ "3")) %>%
  mutate(T2_54 = case_when(T2_54 == "Outright owner" ~ "1", T2_54 == "Mortgagor" ~ "2", T2_54 == "Renter" ~ "3")) %>%
  mutate(T2_55 = case_when(T2_55 == "Outright owner" ~ "1", T2_55 == "Mortgagor" ~ "2", T2_55 == "Renter" ~ "3")) %>%
  mutate(T2_56 = case_when(T2_56 == "Outright owner" ~ "1", T2_56 == "Mortgagor" ~ "2", T2_56 == "Renter" ~ "3")) %>%
  mutate(T2_57 = case_when(T2_57 == "Outright owner" ~ "1", T2_57 == "Mortgagor" ~ "2", T2_57 == "Renter" ~ "3")) %>%
  mutate(T2_58 = case_when(T2_58 == "Outright owner" ~ "1", T2_58 == "Mortgagor" ~ "2", T2_58 == "Renter" ~ "3")) %>%
  mutate(T2_59 = case_when(T2_59 == "Outright owner" ~ "1", T2_59 == "Mortgagor" ~ "2", T2_59 == "Renter" ~ "3")) %>%
  mutate(T2_60 = case_when(T2_60 == "Outright owner" ~ "1", T2_60 == "Mortgagor" ~ "2", T2_60 == "Renter" ~ "3")) %>%
  mutate(T2_61 = case_when(T2_61 == "Outright owner" ~ "1", T2_61 == "Mortgagor" ~ "2", T2_61 == "Renter" ~ "3")) %>%
  mutate(T2_62 = case_when(T2_62 == "Outright owner" ~ "1", T2_62 == "Mortgagor" ~ "2", T2_62 == "Renter" ~ "3")) %>%
  mutate(T2_63 = case_when(T2_63 == "Outright owner" ~ "1", T2_63 == "Mortgagor" ~ "2", T2_63 == "Renter" ~ "3")) %>%
  mutate(T2_64 = case_when(T2_64 == "Outright owner" ~ "1", T2_64 == "Mortgagor" ~ "2", T2_64 == "Renter" ~ "3")) %>%
  mutate(T2_65 = case_when(T2_65 == "Outright owner" ~ "1", T2_65 == "Mortgagor" ~ "2", T2_65 == "Renter" ~ "3"))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~factor(., levels = 0:3)))

# Save start time
start <- Sys.time()

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs", "start")))

# Create containers for results
results_renters <- listenv()
results_outright <- listenv()
results_mortgage <- listenv()

# Set up parallel computing with max 30 cores
workers <- as.numeric(availableCores())
workers <- pmin(45, workers)

plan(multisession, workers = workers)

# Iterate through age range
for (i in c(last_age:51)) {

# Define treatment, outcome, censoring, and confounder variables
treatment <- paste0("T2_", 50:(i - 1))
outcome <- paste0("Y_", 51:i)
censoring <- paste0("C_", 50:(i - 1))
baseline <- c("B1", "B2", "B3", "B4")

vars <- data_wide %>% select(starts_with(c("L"))) %>% names()

time_vary = list()

for (tp in c(50:(i - 1))) {
  time_vary_new <- c(vars[str_detect(vars, str_pad(tp, 2, pad = "0"))])
  
  time_vary[[length(time_vary) + 1]] <- time_vary_new}

  # Initialize TMLE for renters aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "2", "3", "3"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))

  results_renters[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  # Initialize TMLE for outright owners aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "2" | . == "3", "1", "1"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_outright[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}
  
  # Initialize TMLE for mortgagors aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "3", "2", "2"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_mortgage[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  print(paste0("Initialized TMLE for age ", i, "."))

  rm(time_vary_new, tp, shifted)

}

# Gather results
results_renters <- as.list(results_renters)
results_outright <- as.list(results_outright)
results_mortgage <- as.list(results_mortgage)

end <- Sys.time()

print(paste0("Estimation completed at ", paste(hour(end), minute(end), sep = ":"), " after ", round(difftime(end, start, units = "mins"), 0), " minutes."))

rm(treatment, outcome, censoring, time_vary, baseline, workers, i, start, end)

# Clean results
contrasts_outright <- data.frame()
contrasts_mortgage <- data.frame()
results <- data.frame()

for (i in c(51:last_age)) {
  
  cntr <- lmtp_contrast(results_outright[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_outright <- rbind(contrasts_outright, cntr$vals)
  
  cntr <- lmtp_contrast(results_mortgage[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_mortgage <- rbind(contrasts_mortgage, cntr$vals)
  
  rslt <- tidy(results_renters[[i]])
  rslt$age <- i
  rslt$group <- "Renters"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_outright[[i]])
  rslt$age <- i
  rslt$group <- "Outright owners"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_mortgage[[i]])
  rslt$age <- i
  rslt$group <- "Owner w/ mortgage"
  results <- rbind(results, rslt)
  
  rm(cntr, rslt)
  
}

# Covert probability estimate at age 51 into survival
contrasts_outright$age <- c(51:last_age)
contrasts_outright$theta <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$theta, contrasts_outright$theta)
contrasts_outright$conf.low <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.low, contrasts_outright$conf.low)
contrasts_outright$conf.high <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.high, contrasts_outright$conf.high)

contrasts_mortgage$age <- c(51:last_age)
contrasts_mortgage$theta <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$theta, contrasts_mortgage$theta)
contrasts_mortgage$conf.low <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.low, contrasts_mortgage$conf.low)
contrasts_mortgage$conf.high <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.high, contrasts_mortgage$conf.high)

results$estimate <- ifelse(results$age == 51, 1 - results$estimate, results$estimate)
results$conf.low <- ifelse(results$age == 51, 1 - results$conf.low, results$conf.low)
results$conf.high <- ifelse(results$age == 51, 1 - results$conf.high, results$conf.high)

rm(i)

#Save results
save.image("outputs/results_imps2/results_de_2_imp4.RData")

```

# de - Imp 5
```{r}

# Load data and choose from imputed data sets
load("data/data_final_de.RData")

data_wide <- data_de_imp_wide_5

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs")))

data_wide <- data_wide %>% select(-starts_with(c("T1", "T3")))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~as.character(.)))

data_wide <- data_wide %>%
  mutate(T2_50 = case_when(T2_50 == "Outright owner" ~ "1", T2_50 == "Mortgagor" ~ "2", T2_50 == "Renter" ~ "3")) %>%
  mutate(T2_51 = case_when(T2_51 == "Outright owner" ~ "1", T2_51 == "Mortgagor" ~ "2", T2_51 == "Renter" ~ "3")) %>%
  mutate(T2_52 = case_when(T2_52 == "Outright owner" ~ "1", T2_52 == "Mortgagor" ~ "2", T2_52 == "Renter" ~ "3")) %>%
  mutate(T2_53 = case_when(T2_53 == "Outright owner" ~ "1", T2_53 == "Mortgagor" ~ "2", T2_53 == "Renter" ~ "3")) %>%
  mutate(T2_54 = case_when(T2_54 == "Outright owner" ~ "1", T2_54 == "Mortgagor" ~ "2", T2_54 == "Renter" ~ "3")) %>%
  mutate(T2_55 = case_when(T2_55 == "Outright owner" ~ "1", T2_55 == "Mortgagor" ~ "2", T2_55 == "Renter" ~ "3")) %>%
  mutate(T2_56 = case_when(T2_56 == "Outright owner" ~ "1", T2_56 == "Mortgagor" ~ "2", T2_56 == "Renter" ~ "3")) %>%
  mutate(T2_57 = case_when(T2_57 == "Outright owner" ~ "1", T2_57 == "Mortgagor" ~ "2", T2_57 == "Renter" ~ "3")) %>%
  mutate(T2_58 = case_when(T2_58 == "Outright owner" ~ "1", T2_58 == "Mortgagor" ~ "2", T2_58 == "Renter" ~ "3")) %>%
  mutate(T2_59 = case_when(T2_59 == "Outright owner" ~ "1", T2_59 == "Mortgagor" ~ "2", T2_59 == "Renter" ~ "3")) %>%
  mutate(T2_60 = case_when(T2_60 == "Outright owner" ~ "1", T2_60 == "Mortgagor" ~ "2", T2_60 == "Renter" ~ "3")) %>%
  mutate(T2_61 = case_when(T2_61 == "Outright owner" ~ "1", T2_61 == "Mortgagor" ~ "2", T2_61 == "Renter" ~ "3")) %>%
  mutate(T2_62 = case_when(T2_62 == "Outright owner" ~ "1", T2_62 == "Mortgagor" ~ "2", T2_62 == "Renter" ~ "3")) %>%
  mutate(T2_63 = case_when(T2_63 == "Outright owner" ~ "1", T2_63 == "Mortgagor" ~ "2", T2_63 == "Renter" ~ "3")) %>%
  mutate(T2_64 = case_when(T2_64 == "Outright owner" ~ "1", T2_64 == "Mortgagor" ~ "2", T2_64 == "Renter" ~ "3")) %>%
  mutate(T2_65 = case_when(T2_65 == "Outright owner" ~ "1", T2_65 == "Mortgagor" ~ "2", T2_65 == "Renter" ~ "3"))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~factor(., levels = 0:3)))

# Save start time
start <- Sys.time()

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs", "start")))

# Create containers for results
results_renters <- listenv()
results_outright <- listenv()
results_mortgage <- listenv()

# Set up parallel computing with max 30 cores
workers <- as.numeric(availableCores())
workers <- pmin(45, workers)

plan(multisession, workers = workers)

# Iterate through age range
for (i in c(last_age:51)) {

# Define treatment, outcome, censoring, and confounder variables
treatment <- paste0("T2_", 50:(i - 1))
outcome <- paste0("Y_", 51:i)
censoring <- paste0("C_", 50:(i - 1))
baseline <- c("B1", "B2", "B3", "B4")

vars <- data_wide %>% select(starts_with(c("L"))) %>% names()

time_vary = list()

for (tp in c(50:(i - 1))) {
  time_vary_new <- c(vars[str_detect(vars, str_pad(tp, 2, pad = "0"))])
  
  time_vary[[length(time_vary) + 1]] <- time_vary_new}

  # Initialize TMLE for renters aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "2", "3", "3"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))

  results_renters[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  # Initialize TMLE for outright owners aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "2" | . == "3", "1", "1"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_outright[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}
  
  # Initialize TMLE for mortgagors aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "3", "2", "2"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_mortgage[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  print(paste0("Initialized TMLE for age ", i, "."))

  rm(time_vary_new, tp, shifted)

}

# Gather results
results_renters <- as.list(results_renters)
results_outright <- as.list(results_outright)
results_mortgage <- as.list(results_mortgage)

end <- Sys.time()

print(paste0("Estimation completed at ", paste(hour(end), minute(end), sep = ":"), " after ", round(difftime(end, start, units = "mins"), 0), " minutes."))

rm(treatment, outcome, censoring, time_vary, baseline, workers, i, start, end)

# Clean results
contrasts_outright <- data.frame()
contrasts_mortgage <- data.frame()
results <- data.frame()

for (i in c(51:last_age)) {
  
  cntr <- lmtp_contrast(results_outright[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_outright <- rbind(contrasts_outright, cntr$vals)
  
  cntr <- lmtp_contrast(results_mortgage[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_mortgage <- rbind(contrasts_mortgage, cntr$vals)
  
  rslt <- tidy(results_renters[[i]])
  rslt$age <- i
  rslt$group <- "Renters"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_outright[[i]])
  rslt$age <- i
  rslt$group <- "Outright owners"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_mortgage[[i]])
  rslt$age <- i
  rslt$group <- "Owner w/ mortgage"
  results <- rbind(results, rslt)
  
  rm(cntr, rslt)
  
}

# Covert probability estimate at age 51 into survival
contrasts_outright$age <- c(51:last_age)
contrasts_outright$theta <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$theta, contrasts_outright$theta)
contrasts_outright$conf.low <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.low, contrasts_outright$conf.low)
contrasts_outright$conf.high <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.high, contrasts_outright$conf.high)

contrasts_mortgage$age <- c(51:last_age)
contrasts_mortgage$theta <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$theta, contrasts_mortgage$theta)
contrasts_mortgage$conf.low <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.low, contrasts_mortgage$conf.low)
contrasts_mortgage$conf.high <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.high, contrasts_mortgage$conf.high)

results$estimate <- ifelse(results$age == 51, 1 - results$estimate, results$estimate)
results$conf.low <- ifelse(results$age == 51, 1 - results$conf.low, results$conf.low)
results$conf.high <- ifelse(results$age == 51, 1 - results$conf.high, results$conf.high)

rm(i)

#Save results
save.image("outputs/results_imps2/results_de_2_imp5.RData")

```

# de - Imp 6
```{r}

# Load data and choose from imputed data sets
load("data/data_final_de.RData")

data_wide <- data_de_imp_wide_6

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs")))

data_wide <- data_wide %>% select(-starts_with(c("T1", "T3")))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~as.character(.)))

data_wide <- data_wide %>%
  mutate(T2_50 = case_when(T2_50 == "Outright owner" ~ "1", T2_50 == "Mortgagor" ~ "2", T2_50 == "Renter" ~ "3")) %>%
  mutate(T2_51 = case_when(T2_51 == "Outright owner" ~ "1", T2_51 == "Mortgagor" ~ "2", T2_51 == "Renter" ~ "3")) %>%
  mutate(T2_52 = case_when(T2_52 == "Outright owner" ~ "1", T2_52 == "Mortgagor" ~ "2", T2_52 == "Renter" ~ "3")) %>%
  mutate(T2_53 = case_when(T2_53 == "Outright owner" ~ "1", T2_53 == "Mortgagor" ~ "2", T2_53 == "Renter" ~ "3")) %>%
  mutate(T2_54 = case_when(T2_54 == "Outright owner" ~ "1", T2_54 == "Mortgagor" ~ "2", T2_54 == "Renter" ~ "3")) %>%
  mutate(T2_55 = case_when(T2_55 == "Outright owner" ~ "1", T2_55 == "Mortgagor" ~ "2", T2_55 == "Renter" ~ "3")) %>%
  mutate(T2_56 = case_when(T2_56 == "Outright owner" ~ "1", T2_56 == "Mortgagor" ~ "2", T2_56 == "Renter" ~ "3")) %>%
  mutate(T2_57 = case_when(T2_57 == "Outright owner" ~ "1", T2_57 == "Mortgagor" ~ "2", T2_57 == "Renter" ~ "3")) %>%
  mutate(T2_58 = case_when(T2_58 == "Outright owner" ~ "1", T2_58 == "Mortgagor" ~ "2", T2_58 == "Renter" ~ "3")) %>%
  mutate(T2_59 = case_when(T2_59 == "Outright owner" ~ "1", T2_59 == "Mortgagor" ~ "2", T2_59 == "Renter" ~ "3")) %>%
  mutate(T2_60 = case_when(T2_60 == "Outright owner" ~ "1", T2_60 == "Mortgagor" ~ "2", T2_60 == "Renter" ~ "3")) %>%
  mutate(T2_61 = case_when(T2_61 == "Outright owner" ~ "1", T2_61 == "Mortgagor" ~ "2", T2_61 == "Renter" ~ "3")) %>%
  mutate(T2_62 = case_when(T2_62 == "Outright owner" ~ "1", T2_62 == "Mortgagor" ~ "2", T2_62 == "Renter" ~ "3")) %>%
  mutate(T2_63 = case_when(T2_63 == "Outright owner" ~ "1", T2_63 == "Mortgagor" ~ "2", T2_63 == "Renter" ~ "3")) %>%
  mutate(T2_64 = case_when(T2_64 == "Outright owner" ~ "1", T2_64 == "Mortgagor" ~ "2", T2_64 == "Renter" ~ "3")) %>%
  mutate(T2_65 = case_when(T2_65 == "Outright owner" ~ "1", T2_65 == "Mortgagor" ~ "2", T2_65 == "Renter" ~ "3"))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~factor(., levels = 0:3)))

# Save start time
start <- Sys.time()

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs", "start")))

# Create containers for results
results_renters <- listenv()
results_outright <- listenv()
results_mortgage <- listenv()

# Set up parallel computing with max 30 cores
workers <- as.numeric(availableCores())
workers <- pmin(45, workers)

plan(multisession, workers = workers)

# Iterate through age range
for (i in c(last_age:51)) {

# Define treatment, outcome, censoring, and confounder variables
treatment <- paste0("T2_", 50:(i - 1))
outcome <- paste0("Y_", 51:i)
censoring <- paste0("C_", 50:(i - 1))
baseline <- c("B1", "B2", "B3", "B4")

vars <- data_wide %>% select(starts_with(c("L"))) %>% names()

time_vary = list()

for (tp in c(50:(i - 1))) {
  time_vary_new <- c(vars[str_detect(vars, str_pad(tp, 2, pad = "0"))])
  
  time_vary[[length(time_vary) + 1]] <- time_vary_new}

  # Initialize TMLE for renters aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "2", "3", "3"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))

  results_renters[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  # Initialize TMLE for outright owners aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "2" | . == "3", "1", "1"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_outright[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}
  
  # Initialize TMLE for mortgagors aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "3", "2", "2"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_mortgage[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  print(paste0("Initialized TMLE for age ", i, "."))

  rm(time_vary_new, tp, shifted)

}

# Gather results
results_renters <- as.list(results_renters)
results_outright <- as.list(results_outright)
results_mortgage <- as.list(results_mortgage)

end <- Sys.time()

print(paste0("Estimation completed at ", paste(hour(end), minute(end), sep = ":"), " after ", round(difftime(end, start, units = "mins"), 0), " minutes."))

rm(treatment, outcome, censoring, time_vary, baseline, workers, i, start, end)

# Clean results
contrasts_outright <- data.frame()
contrasts_mortgage <- data.frame()
results <- data.frame()

for (i in c(51:last_age)) {
  
  cntr <- lmtp_contrast(results_outright[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_outright <- rbind(contrasts_outright, cntr$vals)
  
  cntr <- lmtp_contrast(results_mortgage[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_mortgage <- rbind(contrasts_mortgage, cntr$vals)
  
  rslt <- tidy(results_renters[[i]])
  rslt$age <- i
  rslt$group <- "Renters"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_outright[[i]])
  rslt$age <- i
  rslt$group <- "Outright owners"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_mortgage[[i]])
  rslt$age <- i
  rslt$group <- "Owner w/ mortgage"
  results <- rbind(results, rslt)
  
  rm(cntr, rslt)
  
}

# Covert probability estimate at age 51 into survival
contrasts_outright$age <- c(51:last_age)
contrasts_outright$theta <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$theta, contrasts_outright$theta)
contrasts_outright$conf.low <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.low, contrasts_outright$conf.low)
contrasts_outright$conf.high <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.high, contrasts_outright$conf.high)

contrasts_mortgage$age <- c(51:last_age)
contrasts_mortgage$theta <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$theta, contrasts_mortgage$theta)
contrasts_mortgage$conf.low <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.low, contrasts_mortgage$conf.low)
contrasts_mortgage$conf.high <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.high, contrasts_mortgage$conf.high)

results$estimate <- ifelse(results$age == 51, 1 - results$estimate, results$estimate)
results$conf.low <- ifelse(results$age == 51, 1 - results$conf.low, results$conf.low)
results$conf.high <- ifelse(results$age == 51, 1 - results$conf.high, results$conf.high)

rm(i)

#Save results
save.image("outputs/results_imps2/results_de_2_imp6.RData")

```

# de - Imp 7
```{r}

# Load data and choose from imputed data sets
load("data/data_final_de.RData")

data_wide <- data_de_imp_wide_7

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs")))

data_wide <- data_wide %>% select(-starts_with(c("T1", "T3")))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~as.character(.)))

data_wide <- data_wide %>%
  mutate(T2_50 = case_when(T2_50 == "Outright owner" ~ "1", T2_50 == "Mortgagor" ~ "2", T2_50 == "Renter" ~ "3")) %>%
  mutate(T2_51 = case_when(T2_51 == "Outright owner" ~ "1", T2_51 == "Mortgagor" ~ "2", T2_51 == "Renter" ~ "3")) %>%
  mutate(T2_52 = case_when(T2_52 == "Outright owner" ~ "1", T2_52 == "Mortgagor" ~ "2", T2_52 == "Renter" ~ "3")) %>%
  mutate(T2_53 = case_when(T2_53 == "Outright owner" ~ "1", T2_53 == "Mortgagor" ~ "2", T2_53 == "Renter" ~ "3")) %>%
  mutate(T2_54 = case_when(T2_54 == "Outright owner" ~ "1", T2_54 == "Mortgagor" ~ "2", T2_54 == "Renter" ~ "3")) %>%
  mutate(T2_55 = case_when(T2_55 == "Outright owner" ~ "1", T2_55 == "Mortgagor" ~ "2", T2_55 == "Renter" ~ "3")) %>%
  mutate(T2_56 = case_when(T2_56 == "Outright owner" ~ "1", T2_56 == "Mortgagor" ~ "2", T2_56 == "Renter" ~ "3")) %>%
  mutate(T2_57 = case_when(T2_57 == "Outright owner" ~ "1", T2_57 == "Mortgagor" ~ "2", T2_57 == "Renter" ~ "3")) %>%
  mutate(T2_58 = case_when(T2_58 == "Outright owner" ~ "1", T2_58 == "Mortgagor" ~ "2", T2_58 == "Renter" ~ "3")) %>%
  mutate(T2_59 = case_when(T2_59 == "Outright owner" ~ "1", T2_59 == "Mortgagor" ~ "2", T2_59 == "Renter" ~ "3")) %>%
  mutate(T2_60 = case_when(T2_60 == "Outright owner" ~ "1", T2_60 == "Mortgagor" ~ "2", T2_60 == "Renter" ~ "3")) %>%
  mutate(T2_61 = case_when(T2_61 == "Outright owner" ~ "1", T2_61 == "Mortgagor" ~ "2", T2_61 == "Renter" ~ "3")) %>%
  mutate(T2_62 = case_when(T2_62 == "Outright owner" ~ "1", T2_62 == "Mortgagor" ~ "2", T2_62 == "Renter" ~ "3")) %>%
  mutate(T2_63 = case_when(T2_63 == "Outright owner" ~ "1", T2_63 == "Mortgagor" ~ "2", T2_63 == "Renter" ~ "3")) %>%
  mutate(T2_64 = case_when(T2_64 == "Outright owner" ~ "1", T2_64 == "Mortgagor" ~ "2", T2_64 == "Renter" ~ "3")) %>%
  mutate(T2_65 = case_when(T2_65 == "Outright owner" ~ "1", T2_65 == "Mortgagor" ~ "2", T2_65 == "Renter" ~ "3"))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~factor(., levels = 0:3)))

# Save start time
start <- Sys.time()

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs", "start")))

# Create containers for results
results_renters <- listenv()
results_outright <- listenv()
results_mortgage <- listenv()

# Set up parallel computing with max 30 cores
workers <- as.numeric(availableCores())
workers <- pmin(45, workers)

plan(multisession, workers = workers)

# Iterate through age range
for (i in c(last_age:51)) {

# Define treatment, outcome, censoring, and confounder variables
treatment <- paste0("T2_", 50:(i - 1))
outcome <- paste0("Y_", 51:i)
censoring <- paste0("C_", 50:(i - 1))
baseline <- c("B1", "B2", "B3", "B4")

vars <- data_wide %>% select(starts_with(c("L"))) %>% names()

time_vary = list()

for (tp in c(50:(i - 1))) {
  time_vary_new <- c(vars[str_detect(vars, str_pad(tp, 2, pad = "0"))])
  
  time_vary[[length(time_vary) + 1]] <- time_vary_new}

  # Initialize TMLE for renters aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "2", "3", "3"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))

  results_renters[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  # Initialize TMLE for outright owners aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "2" | . == "3", "1", "1"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_outright[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}
  
  # Initialize TMLE for mortgagors aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "3", "2", "2"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_mortgage[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  print(paste0("Initialized TMLE for age ", i, "."))

  rm(time_vary_new, tp, shifted)

}

# Gather results
results_renters <- as.list(results_renters)
results_outright <- as.list(results_outright)
results_mortgage <- as.list(results_mortgage)

end <- Sys.time()

print(paste0("Estimation completed at ", paste(hour(end), minute(end), sep = ":"), " after ", round(difftime(end, start, units = "mins"), 0), " minutes."))

rm(treatment, outcome, censoring, time_vary, baseline, workers, i, start, end)

# Clean results
contrasts_outright <- data.frame()
contrasts_mortgage <- data.frame()
results <- data.frame()

for (i in c(51:last_age)) {
  
  cntr <- lmtp_contrast(results_outright[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_outright <- rbind(contrasts_outright, cntr$vals)
  
  cntr <- lmtp_contrast(results_mortgage[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_mortgage <- rbind(contrasts_mortgage, cntr$vals)
  
  rslt <- tidy(results_renters[[i]])
  rslt$age <- i
  rslt$group <- "Renters"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_outright[[i]])
  rslt$age <- i
  rslt$group <- "Outright owners"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_mortgage[[i]])
  rslt$age <- i
  rslt$group <- "Owner w/ mortgage"
  results <- rbind(results, rslt)
  
  rm(cntr, rslt)
  
}

# Covert probability estimate at age 51 into survival
contrasts_outright$age <- c(51:last_age)
contrasts_outright$theta <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$theta, contrasts_outright$theta)
contrasts_outright$conf.low <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.low, contrasts_outright$conf.low)
contrasts_outright$conf.high <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.high, contrasts_outright$conf.high)

contrasts_mortgage$age <- c(51:last_age)
contrasts_mortgage$theta <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$theta, contrasts_mortgage$theta)
contrasts_mortgage$conf.low <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.low, contrasts_mortgage$conf.low)
contrasts_mortgage$conf.high <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.high, contrasts_mortgage$conf.high)

results$estimate <- ifelse(results$age == 51, 1 - results$estimate, results$estimate)
results$conf.low <- ifelse(results$age == 51, 1 - results$conf.low, results$conf.low)
results$conf.high <- ifelse(results$age == 51, 1 - results$conf.high, results$conf.high)

rm(i)

#Save results
save.image("outputs/results_imps2/results_de_2_imp7.RData")

```

# de - Imp 8
```{r}

# Load data and choose from imputed data sets
load("data/data_final_de.RData")

data_wide <- data_de_imp_wide_8

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs")))

data_wide <- data_wide %>% select(-starts_with(c("T1", "T3")))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~as.character(.)))

data_wide <- data_wide %>%
  mutate(T2_50 = case_when(T2_50 == "Outright owner" ~ "1", T2_50 == "Mortgagor" ~ "2", T2_50 == "Renter" ~ "3")) %>%
  mutate(T2_51 = case_when(T2_51 == "Outright owner" ~ "1", T2_51 == "Mortgagor" ~ "2", T2_51 == "Renter" ~ "3")) %>%
  mutate(T2_52 = case_when(T2_52 == "Outright owner" ~ "1", T2_52 == "Mortgagor" ~ "2", T2_52 == "Renter" ~ "3")) %>%
  mutate(T2_53 = case_when(T2_53 == "Outright owner" ~ "1", T2_53 == "Mortgagor" ~ "2", T2_53 == "Renter" ~ "3")) %>%
  mutate(T2_54 = case_when(T2_54 == "Outright owner" ~ "1", T2_54 == "Mortgagor" ~ "2", T2_54 == "Renter" ~ "3")) %>%
  mutate(T2_55 = case_when(T2_55 == "Outright owner" ~ "1", T2_55 == "Mortgagor" ~ "2", T2_55 == "Renter" ~ "3")) %>%
  mutate(T2_56 = case_when(T2_56 == "Outright owner" ~ "1", T2_56 == "Mortgagor" ~ "2", T2_56 == "Renter" ~ "3")) %>%
  mutate(T2_57 = case_when(T2_57 == "Outright owner" ~ "1", T2_57 == "Mortgagor" ~ "2", T2_57 == "Renter" ~ "3")) %>%
  mutate(T2_58 = case_when(T2_58 == "Outright owner" ~ "1", T2_58 == "Mortgagor" ~ "2", T2_58 == "Renter" ~ "3")) %>%
  mutate(T2_59 = case_when(T2_59 == "Outright owner" ~ "1", T2_59 == "Mortgagor" ~ "2", T2_59 == "Renter" ~ "3")) %>%
  mutate(T2_60 = case_when(T2_60 == "Outright owner" ~ "1", T2_60 == "Mortgagor" ~ "2", T2_60 == "Renter" ~ "3")) %>%
  mutate(T2_61 = case_when(T2_61 == "Outright owner" ~ "1", T2_61 == "Mortgagor" ~ "2", T2_61 == "Renter" ~ "3")) %>%
  mutate(T2_62 = case_when(T2_62 == "Outright owner" ~ "1", T2_62 == "Mortgagor" ~ "2", T2_62 == "Renter" ~ "3")) %>%
  mutate(T2_63 = case_when(T2_63 == "Outright owner" ~ "1", T2_63 == "Mortgagor" ~ "2", T2_63 == "Renter" ~ "3")) %>%
  mutate(T2_64 = case_when(T2_64 == "Outright owner" ~ "1", T2_64 == "Mortgagor" ~ "2", T2_64 == "Renter" ~ "3")) %>%
  mutate(T2_65 = case_when(T2_65 == "Outright owner" ~ "1", T2_65 == "Mortgagor" ~ "2", T2_65 == "Renter" ~ "3"))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~factor(., levels = 0:3)))

# Save start time
start <- Sys.time()

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs", "start")))

# Create containers for results
results_renters <- listenv()
results_outright <- listenv()
results_mortgage <- listenv()

# Set up parallel computing with max 30 cores
workers <- as.numeric(availableCores())
workers <- pmin(45, workers)

plan(multisession, workers = workers)

# Iterate through age range
for (i in c(last_age:51)) {

# Define treatment, outcome, censoring, and confounder variables
treatment <- paste0("T2_", 50:(i - 1))
outcome <- paste0("Y_", 51:i)
censoring <- paste0("C_", 50:(i - 1))
baseline <- c("B1", "B2", "B3", "B4")

vars <- data_wide %>% select(starts_with(c("L"))) %>% names()

time_vary = list()

for (tp in c(50:(i - 1))) {
  time_vary_new <- c(vars[str_detect(vars, str_pad(tp, 2, pad = "0"))])
  
  time_vary[[length(time_vary) + 1]] <- time_vary_new}

  # Initialize TMLE for renters aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "2", "3", "3"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))

  results_renters[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  # Initialize TMLE for outright owners aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "2" | . == "3", "1", "1"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_outright[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}
  
  # Initialize TMLE for mortgagors aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "3", "2", "2"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_mortgage[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  print(paste0("Initialized TMLE for age ", i, "."))

  rm(time_vary_new, tp, shifted)

}

# Gather results
results_renters <- as.list(results_renters)
results_outright <- as.list(results_outright)
results_mortgage <- as.list(results_mortgage)

end <- Sys.time()

print(paste0("Estimation completed at ", paste(hour(end), minute(end), sep = ":"), " after ", round(difftime(end, start, units = "mins"), 0), " minutes."))

rm(treatment, outcome, censoring, time_vary, baseline, workers, i, start, end)

# Clean results
contrasts_outright <- data.frame()
contrasts_mortgage <- data.frame()
results <- data.frame()

for (i in c(51:last_age)) {
  
  cntr <- lmtp_contrast(results_outright[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_outright <- rbind(contrasts_outright, cntr$vals)
  
  cntr <- lmtp_contrast(results_mortgage[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_mortgage <- rbind(contrasts_mortgage, cntr$vals)
  
  rslt <- tidy(results_renters[[i]])
  rslt$age <- i
  rslt$group <- "Renters"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_outright[[i]])
  rslt$age <- i
  rslt$group <- "Outright owners"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_mortgage[[i]])
  rslt$age <- i
  rslt$group <- "Owner w/ mortgage"
  results <- rbind(results, rslt)
  
  rm(cntr, rslt)
  
}

# Covert probability estimate at age 51 into survival
contrasts_outright$age <- c(51:last_age)
contrasts_outright$theta <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$theta, contrasts_outright$theta)
contrasts_outright$conf.low <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.low, contrasts_outright$conf.low)
contrasts_outright$conf.high <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.high, contrasts_outright$conf.high)

contrasts_mortgage$age <- c(51:last_age)
contrasts_mortgage$theta <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$theta, contrasts_mortgage$theta)
contrasts_mortgage$conf.low <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.low, contrasts_mortgage$conf.low)
contrasts_mortgage$conf.high <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.high, contrasts_mortgage$conf.high)

results$estimate <- ifelse(results$age == 51, 1 - results$estimate, results$estimate)
results$conf.low <- ifelse(results$age == 51, 1 - results$conf.low, results$conf.low)
results$conf.high <- ifelse(results$age == 51, 1 - results$conf.high, results$conf.high)

rm(i)

#Save results
save.image("outputs/results_imps2/results_de_2_imp8.RData")

```

# de - Imp 9
```{r}

# Load data and choose from imputed data sets
load("data/data_final_de.RData")

data_wide <- data_de_imp_wide_9

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs")))

data_wide <- data_wide %>% select(-starts_with(c("T1", "T3")))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~as.character(.)))

data_wide <- data_wide %>%
  mutate(T2_50 = case_when(T2_50 == "Outright owner" ~ "1", T2_50 == "Mortgagor" ~ "2", T2_50 == "Renter" ~ "3")) %>%
  mutate(T2_51 = case_when(T2_51 == "Outright owner" ~ "1", T2_51 == "Mortgagor" ~ "2", T2_51 == "Renter" ~ "3")) %>%
  mutate(T2_52 = case_when(T2_52 == "Outright owner" ~ "1", T2_52 == "Mortgagor" ~ "2", T2_52 == "Renter" ~ "3")) %>%
  mutate(T2_53 = case_when(T2_53 == "Outright owner" ~ "1", T2_53 == "Mortgagor" ~ "2", T2_53 == "Renter" ~ "3")) %>%
  mutate(T2_54 = case_when(T2_54 == "Outright owner" ~ "1", T2_54 == "Mortgagor" ~ "2", T2_54 == "Renter" ~ "3")) %>%
  mutate(T2_55 = case_when(T2_55 == "Outright owner" ~ "1", T2_55 == "Mortgagor" ~ "2", T2_55 == "Renter" ~ "3")) %>%
  mutate(T2_56 = case_when(T2_56 == "Outright owner" ~ "1", T2_56 == "Mortgagor" ~ "2", T2_56 == "Renter" ~ "3")) %>%
  mutate(T2_57 = case_when(T2_57 == "Outright owner" ~ "1", T2_57 == "Mortgagor" ~ "2", T2_57 == "Renter" ~ "3")) %>%
  mutate(T2_58 = case_when(T2_58 == "Outright owner" ~ "1", T2_58 == "Mortgagor" ~ "2", T2_58 == "Renter" ~ "3")) %>%
  mutate(T2_59 = case_when(T2_59 == "Outright owner" ~ "1", T2_59 == "Mortgagor" ~ "2", T2_59 == "Renter" ~ "3")) %>%
  mutate(T2_60 = case_when(T2_60 == "Outright owner" ~ "1", T2_60 == "Mortgagor" ~ "2", T2_60 == "Renter" ~ "3")) %>%
  mutate(T2_61 = case_when(T2_61 == "Outright owner" ~ "1", T2_61 == "Mortgagor" ~ "2", T2_61 == "Renter" ~ "3")) %>%
  mutate(T2_62 = case_when(T2_62 == "Outright owner" ~ "1", T2_62 == "Mortgagor" ~ "2", T2_62 == "Renter" ~ "3")) %>%
  mutate(T2_63 = case_when(T2_63 == "Outright owner" ~ "1", T2_63 == "Mortgagor" ~ "2", T2_63 == "Renter" ~ "3")) %>%
  mutate(T2_64 = case_when(T2_64 == "Outright owner" ~ "1", T2_64 == "Mortgagor" ~ "2", T2_64 == "Renter" ~ "3")) %>%
  mutate(T2_65 = case_when(T2_65 == "Outright owner" ~ "1", T2_65 == "Mortgagor" ~ "2", T2_65 == "Renter" ~ "3"))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~factor(., levels = 0:3)))

# Save start time
start <- Sys.time()

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs", "start")))

# Create containers for results
results_renters <- listenv()
results_outright <- listenv()
results_mortgage <- listenv()

# Set up parallel computing with max 30 cores
workers <- as.numeric(availableCores())
workers <- pmin(45, workers)

plan(multisession, workers = workers)

# Iterate through age range
for (i in c(last_age:51)) {

# Define treatment, outcome, censoring, and confounder variables
treatment <- paste0("T2_", 50:(i - 1))
outcome <- paste0("Y_", 51:i)
censoring <- paste0("C_", 50:(i - 1))
baseline <- c("B1", "B2", "B3", "B4")

vars <- data_wide %>% select(starts_with(c("L"))) %>% names()

time_vary = list()

for (tp in c(50:(i - 1))) {
  time_vary_new <- c(vars[str_detect(vars, str_pad(tp, 2, pad = "0"))])
  
  time_vary[[length(time_vary) + 1]] <- time_vary_new}

  # Initialize TMLE for renters aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "2", "3", "3"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))

  results_renters[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  # Initialize TMLE for outright owners aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "2" | . == "3", "1", "1"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_outright[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}
  
  # Initialize TMLE for mortgagors aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "3", "2", "2"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_mortgage[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  print(paste0("Initialized TMLE for age ", i, "."))

  rm(time_vary_new, tp, shifted)

}

# Gather results
results_renters <- as.list(results_renters)
results_outright <- as.list(results_outright)
results_mortgage <- as.list(results_mortgage)

end <- Sys.time()

print(paste0("Estimation completed at ", paste(hour(end), minute(end), sep = ":"), " after ", round(difftime(end, start, units = "mins"), 0), " minutes."))

rm(treatment, outcome, censoring, time_vary, baseline, workers, i, start, end)

# Clean results
contrasts_outright <- data.frame()
contrasts_mortgage <- data.frame()
results <- data.frame()

for (i in c(51:last_age)) {
  
  cntr <- lmtp_contrast(results_outright[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_outright <- rbind(contrasts_outright, cntr$vals)
  
  cntr <- lmtp_contrast(results_mortgage[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_mortgage <- rbind(contrasts_mortgage, cntr$vals)
  
  rslt <- tidy(results_renters[[i]])
  rslt$age <- i
  rslt$group <- "Renters"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_outright[[i]])
  rslt$age <- i
  rslt$group <- "Outright owners"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_mortgage[[i]])
  rslt$age <- i
  rslt$group <- "Owner w/ mortgage"
  results <- rbind(results, rslt)
  
  rm(cntr, rslt)
  
}

# Covert probability estimate at age 51 into survival
contrasts_outright$age <- c(51:last_age)
contrasts_outright$theta <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$theta, contrasts_outright$theta)
contrasts_outright$conf.low <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.low, contrasts_outright$conf.low)
contrasts_outright$conf.high <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.high, contrasts_outright$conf.high)

contrasts_mortgage$age <- c(51:last_age)
contrasts_mortgage$theta <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$theta, contrasts_mortgage$theta)
contrasts_mortgage$conf.low <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.low, contrasts_mortgage$conf.low)
contrasts_mortgage$conf.high <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.high, contrasts_mortgage$conf.high)

results$estimate <- ifelse(results$age == 51, 1 - results$estimate, results$estimate)
results$conf.low <- ifelse(results$age == 51, 1 - results$conf.low, results$conf.low)
results$conf.high <- ifelse(results$age == 51, 1 - results$conf.high, results$conf.high)

rm(i)

#Save results
save.image("outputs/results_imps2/results_de_2_imp9.RData")

```

# de - Imp 10
```{r}

# Load data and choose from imputed data sets
load("data/data_final_de.RData")

data_wide <- data_de_imp_wide_10

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs")))

data_wide <- data_wide %>% select(-starts_with(c("T1", "T3")))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~as.character(.)))

data_wide <- data_wide %>%
  mutate(T2_50 = case_when(T2_50 == "Outright owner" ~ "1", T2_50 == "Mortgagor" ~ "2", T2_50 == "Renter" ~ "3")) %>%
  mutate(T2_51 = case_when(T2_51 == "Outright owner" ~ "1", T2_51 == "Mortgagor" ~ "2", T2_51 == "Renter" ~ "3")) %>%
  mutate(T2_52 = case_when(T2_52 == "Outright owner" ~ "1", T2_52 == "Mortgagor" ~ "2", T2_52 == "Renter" ~ "3")) %>%
  mutate(T2_53 = case_when(T2_53 == "Outright owner" ~ "1", T2_53 == "Mortgagor" ~ "2", T2_53 == "Renter" ~ "3")) %>%
  mutate(T2_54 = case_when(T2_54 == "Outright owner" ~ "1", T2_54 == "Mortgagor" ~ "2", T2_54 == "Renter" ~ "3")) %>%
  mutate(T2_55 = case_when(T2_55 == "Outright owner" ~ "1", T2_55 == "Mortgagor" ~ "2", T2_55 == "Renter" ~ "3")) %>%
  mutate(T2_56 = case_when(T2_56 == "Outright owner" ~ "1", T2_56 == "Mortgagor" ~ "2", T2_56 == "Renter" ~ "3")) %>%
  mutate(T2_57 = case_when(T2_57 == "Outright owner" ~ "1", T2_57 == "Mortgagor" ~ "2", T2_57 == "Renter" ~ "3")) %>%
  mutate(T2_58 = case_when(T2_58 == "Outright owner" ~ "1", T2_58 == "Mortgagor" ~ "2", T2_58 == "Renter" ~ "3")) %>%
  mutate(T2_59 = case_when(T2_59 == "Outright owner" ~ "1", T2_59 == "Mortgagor" ~ "2", T2_59 == "Renter" ~ "3")) %>%
  mutate(T2_60 = case_when(T2_60 == "Outright owner" ~ "1", T2_60 == "Mortgagor" ~ "2", T2_60 == "Renter" ~ "3")) %>%
  mutate(T2_61 = case_when(T2_61 == "Outright owner" ~ "1", T2_61 == "Mortgagor" ~ "2", T2_61 == "Renter" ~ "3")) %>%
  mutate(T2_62 = case_when(T2_62 == "Outright owner" ~ "1", T2_62 == "Mortgagor" ~ "2", T2_62 == "Renter" ~ "3")) %>%
  mutate(T2_63 = case_when(T2_63 == "Outright owner" ~ "1", T2_63 == "Mortgagor" ~ "2", T2_63 == "Renter" ~ "3")) %>%
  mutate(T2_64 = case_when(T2_64 == "Outright owner" ~ "1", T2_64 == "Mortgagor" ~ "2", T2_64 == "Renter" ~ "3")) %>%
  mutate(T2_65 = case_when(T2_65 == "Outright owner" ~ "1", T2_65 == "Mortgagor" ~ "2", T2_65 == "Renter" ~ "3"))

data_wide <- data_wide %>% mutate(across(starts_with("T2_"), ~factor(., levels = 0:3)))

# Save start time
start <- Sys.time()

rm(list = setdiff(ls(), c("data_wide", "last_age", "trim", "folds", "SL_folds", "SL_libs", "start")))

# Create containers for results
results_renters <- listenv()
results_outright <- listenv()
results_mortgage <- listenv()

# Set up parallel computing with max 30 cores
workers <- as.numeric(availableCores())
workers <- pmin(45, workers)

plan(multisession, workers = workers)

# Iterate through age range
for (i in c(last_age:51)) {

# Define treatment, outcome, censoring, and confounder variables
treatment <- paste0("T2_", 50:(i - 1))
outcome <- paste0("Y_", 51:i)
censoring <- paste0("C_", 50:(i - 1))
baseline <- c("B1", "B2", "B3", "B4")

vars <- data_wide %>% select(starts_with(c("L"))) %>% names()

time_vary = list()

for (tp in c(50:(i - 1))) {
  time_vary_new <- c(vars[str_detect(vars, str_pad(tp, 2, pad = "0"))])
  
  time_vary[[length(time_vary) + 1]] <- time_vary_new}

  # Initialize TMLE for renters aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "2", "3", "3"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))

  results_renters[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  # Initialize TMLE for outright owners aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "2" | . == "3", "1", "1"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_outright[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}
  
  # Initialize TMLE for mortgagors aged i
  shifted <- data_wide %>% 
    mutate(across(starts_with("T2_"), ~if_else(. == "1" | . == "3", "2", "2"))) %>%
    mutate(across(starts_with("T2_"), ~factor(., levels = 0:3))) %>%
    mutate(across(starts_with("C_"), ~replace(1, 1, 1)))
  
  results_mortgage[[i]] %<-% {lmtp_tmle(data_wide,
                                      trt = treatment,
                                      outcome = outcome,
                                      baseline = baseline,
                                      time_vary = time_vary,
                                      cens = censoring,
                                      shifted = shifted,
                                      outcome_type = ifelse(i == 51, "binomial", "survival"),
                                      learners_outcome = SL_libs,
                                      learners_trt = SL_libs,
                                      folds = folds,
                                      .trim = trim,
                                      .learners_outcome_folds = SL_folds,
                                      .learners_trt_folds = SL_folds)}

  print(paste0("Initialized TMLE for age ", i, "."))

  rm(time_vary_new, tp, shifted)

}

# Gather results
results_renters <- as.list(results_renters)
results_outright <- as.list(results_outright)
results_mortgage <- as.list(results_mortgage)

end <- Sys.time()

print(paste0("Estimation completed at ", paste(hour(end), minute(end), sep = ":"), " after ", round(difftime(end, start, units = "mins"), 0), " minutes."))

rm(treatment, outcome, censoring, time_vary, baseline, workers, i, start, end)

# Clean results
contrasts_outright <- data.frame()
contrasts_mortgage <- data.frame()
results <- data.frame()

for (i in c(51:last_age)) {
  
  cntr <- lmtp_contrast(results_outright[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_outright <- rbind(contrasts_outright, cntr$vals)
  
  cntr <- lmtp_contrast(results_mortgage[[i]], ref = results_renters[[i]], type = c("additive"))
  cntr$vals$age <- i
  contrasts_mortgage <- rbind(contrasts_mortgage, cntr$vals)
  
  rslt <- tidy(results_renters[[i]])
  rslt$age <- i
  rslt$group <- "Renters"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_outright[[i]])
  rslt$age <- i
  rslt$group <- "Outright owners"
  results <- rbind(results, rslt)
  
  rslt <- tidy(results_mortgage[[i]])
  rslt$age <- i
  rslt$group <- "Owner w/ mortgage"
  results <- rbind(results, rslt)
  
  rm(cntr, rslt)
  
}

# Covert probability estimate at age 51 into survival
contrasts_outright$age <- c(51:last_age)
contrasts_outright$theta <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$theta, contrasts_outright$theta)
contrasts_outright$conf.low <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.low, contrasts_outright$conf.low)
contrasts_outright$conf.high <- ifelse(contrasts_outright$age == 51, (-1) * contrasts_outright$conf.high, contrasts_outright$conf.high)

contrasts_mortgage$age <- c(51:last_age)
contrasts_mortgage$theta <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$theta, contrasts_mortgage$theta)
contrasts_mortgage$conf.low <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.low, contrasts_mortgage$conf.low)
contrasts_mortgage$conf.high <- ifelse(contrasts_mortgage$age == 51, (-1) * contrasts_mortgage$conf.high, contrasts_mortgage$conf.high)

results$estimate <- ifelse(results$age == 51, 1 - results$estimate, results$estimate)
results$conf.low <- ifelse(results$age == 51, 1 - results$conf.low, results$conf.low)
results$conf.high <- ifelse(results$age == 51, 1 - results$conf.high, results$conf.high)

rm(i)

#Save results
save.image("outputs/results_imps2/results_de_2_imp10.RData")

```

```{r}

```
