---
title: "3.2_graphs"
author: "Jan Einhoff"
date: "05/2024"
---

This R markdown file is used to create risk difference plots for the second analysis.

```{r setup}
# Load packages
library("tidyverse")
library("gridExtra")

# Clear workspace
rm(list = ls())

# Load results files
load("outputs/results_de_2.RData")

```

```{r}
contrasts_mortgage$sig <- ifelse(contrasts_mortgage$p.value < 0.05, "Yes", "No")
contrasts_outright$sig <- ifelse(contrasts_outright$p.value < 0.05, "Yes", "No")

plot <- ggplot() +
  geom_hline(yintercept = 0, size = 0.5, lty = 2, color = "red") +
  geom_line(data = contrasts_outright, aes(x = age + 0.15, y = (-1) * theta), color = "lightgrey") +
  geom_line(data = contrasts_mortgage, aes(x = age - 0.15, y = (-1) * theta), color = "lightgrey") +
  geom_point(data = contrasts_outright, aes(x = age + 0.15, y = (-1) * theta, color = sig, shape = "Outright owner"), size = 2) +
  geom_point(data = contrasts_mortgage, aes(x = age - 0.15, y = (-1) * theta, color = sig, shape = "Owner w/ mortgage"), size = 2) +
  geom_errorbar(data = contrasts_outright, aes(x = age + 0.15, ymin = (-1) * conf.low, ymax = (-1) * conf.high, color = sig), width = 0.25) +
  geom_errorbar(data = contrasts_mortgage, aes(x = age - 0.15, ymin = (-1) * conf.low, ymax = (-1) * conf.high, color = sig), width = 0.25) +
  theme_classic() +
  coord_cartesian(xlim = c(51, 65), ylim = c(-0.15, 0.25)) +
  scale_color_manual(values = c("lightgrey", "black")) +
  scale_fill_manual(values = c(1, 2)) +
  guides(colour = "none") +
  theme(axis.text.x = element_text(color = "black"),
        axis.text.y = element_text(color = "black"),
        panel.grid.major.y = element_line(colour = "grey", size = 0.1),
        panel.spacing.x = unit(0, "pt"),
        legend.position=c(.25,.86),
        legend.key = element_rect(colour = "transparent", fill = "transparent"),
        legend.background = element_rect(fill = 'transparent'),
        legend.title = element_blank(),
        strip.placement = 'outside',
        strip.background = element_blank(),
        panel.background = element_blank(),
        plot.background = element_blank()) +
  scale_y_continuous("Risk difference (ATE)", breaks = seq(-0.15, 0.25, 0.05), labels = c("-15pp.", "-10pp.", "-5pp.", "0pp.", "5pp.", "10pp.", "15pp.", "20pp.", "25pp.")) +
  scale_x_continuous("Age", breaks = seq(50, 70, 1))

ggsave("outputs/test.png", height = 5, width = 4, bg = "transparent", plot)

```

```{r}
```
