
```{r setup}
library(tidyverse)
library(survival)
library(survminer)
library(ggsurvfit)
library(gridExtra)
library(pammtools)
library(stargazer)
library(grid)
library(nnet)

rm(list = ls())

load("data_final.RData")
```

```{r}
data <- data %>% filter(country == "Germany")

data <- data %>% na.omit()

data <- data %>% filter(sex == "Male")
```

```{r}
data_first <- data %>% group_by(person_id) %>% filter(age == min(age))

data_empty <- data %>% mutate(employed = NA, employed_lag = NA, homeowner = NA, homeowner_lag = NA) %>% group_by(person_id) %>% filter(age != min(age))
data_empty <- rbind(data_empty, data_first)
data_empty <- data_empty %>% arrange(person_id, age) %>% mutate(retired = NA)
data_empty <- data_empty %>% filter(age != min(age))

rm(data_first)
```

```{r, warning = F, message = F}
model_outcome <- glm(retired ~ as.factor(age)*homeowner_lag + employment_status_lag + education_level + migrant + household_size_lag + marital_status_lag + industry_lag + health_status_lag + region + as.factor(year), data, family = binomial("logit"))

model_employed <- multinom(employment_status ~ homeowner_lag + education_level + migrant + marital_status_lag + occupation_lag + industry_lag + health_status_lag + region + age + I(age^2) + I(age^3) + region + as.factor(year), data)

model_marital <- multinom(marital_status ~ homeowner_lag + education_level + children_any_lag + employment_status + migrant + occupation_lag + health_status_lag + region + age + I(age^2) + I(age^3), data)

#stargazer(model_outcome, type = "text")
#stargazer(model_employed, type = "text")
#stargazer(model_marital, type = "text")
```

```{r, warning = F}

##################################
##### HOMEOWNERS VS. RENTERS ##### 
##################################

runs <- 1
obs <- 2000

df_final = data.frame()

for (r in c(1:runs)) {
  
  df_total = data.frame()
  
  draw <- sample(unique(data_empty$person_id), obs)
  
  data_int1 <- data_empty %>% filter(person_id %in% draw)
  data_int1$homeowner <- "Homeowner"
  data_int1$homeowner_lag <- "Homeowner"
  data_int1$homeowner_type <- "No_mortgage"
  data_int1$homeowner_type_lag <- "No_mortgage"
  
  for(i in 1:nrow(data_int1)) {
    
      row <- data_int1[i,]
      
      ## employment_status
      employment_status_pred <- predict(model_employed, row, type = "probs")
      employment_status_pred <- rmultinom(n = 1, size = 1, prob = employment_status_pred)
      employment_status_pred <- as.data.frame(employment_status_pred)
      employment_status_pred <- employment_status_pred %>% filter(V1 == 1)

      data_int1$employment_status[i] <- rownames(employment_status_pred)
      data_int1 <- data_int1 %>% group_by(person_id) %>% mutate(employment_status_lag = lag(employment_status, n = 1))
      ##
      
      ## marital_status
      marital_status_pred <- predict(model_marital, row, type = "probs")
      marital_status_pred <- rmultinom(n = 1, size = 1, prob = marital_status_pred)
      marital_status_pred <- as.data.frame(marital_status_pred)
      marital_status_pred <- marital_status_pred %>% filter(V1 == 1)

      data_int1$martial_status[i] <- rownames(marital_status_pred)
      data_int1 <- data_int1 %>% group_by(person_id) %>% mutate(martial_status_lag = lag(martial_status, n = 1))
      ##
      
      ## retired
      row$retired <- predict(model_outcome, row, type = "response")
      data_int1$retired[i] <- rbinom(1, 1, prob = row$retired)
      ##
      
      message(paste0("Prediction ", i, " of ", nrow(data_int1), " for intervention: Homeowner in iteration ", r, " of ", runs, "."))
      }
  
  data_int1 <- data_int1 %>% group_by(person_id) %>% filter(!is.na(retired)) %>% mutate(retired = cumsum(retired), retired = cumsum(retired)) %>% filter(retired %in% c(0, 1))
  data_int1 <- survfit2(Surv(enter, exit, retired) ~ 1, data = data_int1) %>% ggsurvfit()
  data_int1 <- data_int1$data
  data_int1 <- data_int1 %>% filter(time %in% c(51:70)) %>% select(time, estimate) %>% arrange(time)
  data_int1 <- rbind(data_int1, c(50, 1))
  data_int1$intervention <- "Homeowner"
  
  df_total <- rbind(df_total, data_int1)
  
  data_int2 <- data_empty %>% filter(person_id %in% draw)
  data_int2$homeowner <- "Renter"
  data_int2$homeowner_lag <- "Renter"
  data_int2$homeowner_type <- "Renter"
  data_int2$homeowner_type_lag <- "Renter"
  
  for(i in 1:nrow(data_int2)) {
    
      row <- data_int2[i,]
      
      ## employment_status
      employment_status_pred <- predict(model_employed, row, type = "probs")
      employment_status_pred <- rmultinom(n = 1, size = 1, prob = employment_status_pred)
      employment_status_pred <- as.data.frame(employment_status_pred)
      employment_status_pred <- employment_status_pred %>% filter(V1 == 1)

      data_int2$employment_status[i] <- rownames(employment_status_pred)
      data_int2 <- data_int2 %>% group_by(person_id) %>% mutate(employment_status_lag = lag(employment_status, n = 1))
      ##
      
      ## marital_status
      marital_status_pred <- predict(model_marital, row, type = "probs")
      marital_status_pred <- rmultinom(n = 1, size = 1, prob = marital_status_pred)
      marital_status_pred <- as.data.frame(marital_status_pred)
      marital_status_pred <- marital_status_pred %>% filter(V1 == 1)

      data_int2$martial_status[i] <- rownames(marital_status_pred)
      data_int2 <- data_int2 %>% group_by(person_id) %>% mutate(martial_status_lag = lag(martial_status, n = 1))
      ##
      
      ## retired
      row$retired <- predict(model_outcome, row, type = "response")
      data_int2$retired[i] <- rbinom(1, 1, prob = row$retired)
      ##
    
      message(paste0("Prediction ", i, " of ", nrow(data_int2), " for intervention: Renter in iteration ", r, " of ", runs, "."))
      }
  
  data_int2 <- data_int2 %>% group_by(person_id) %>% filter(!is.na(retired)) %>% mutate(retired = cumsum(retired), retired = cumsum(retired)) %>% filter(retired %in% c(0, 1))
  data_int2 <- survfit2(Surv(enter, exit, retired) ~ 1, data = data_int2) %>% ggsurvfit()
  data_int2 <- data_int2$data
  data_int2 <- data_int2 %>% filter(time %in% c(51:70)) %>% select(time, estimate) %>% arrange(time)
  data_int2 <- rbind(data_int2, c(50, 1))
  data_int2$intervention <- "Renter"

  df_total <- rbind(df_total, data_int2)
  
  rm(data_int_models)
  
  df_total <- df_total %>%
    spread(key = intervention, value = estimate) %>%
    mutate(diff = Renter - Homeowner, run = paste(r))
  
  df_final <- rbind(df_final, df_total)
  
}

rm(row, draw, i, r, obs, runs, df_total, data_int1, data_int2, model_employed, model_outcome, data_empty)

```

```{r}
survival <- df_final %>%
  ungroup() %>% 
  complete(time, run) %>% 
  arrange(run, time) %>% 
  fill(Homeowner, Renter, diff, .direction = "down")

#survival <- survival %>%
#  group_by(time) %>%
#  mutate(
#    run = as.numeric(run),
#    homeowner_mean = quantile(Homeowner, probs = c(0.5), na.rm = T),
#    renter_mean = quantile(Renter, probs = c(0.5), na.rm = T),
#    diff_mean = quantile(diff, probs = c(0.5), na.rm = T),
#    diff_lower = quantile(diff, probs = c(0.025), na.rm = T),
#    diff_upper = quantile(diff, probs = c(0.975), na.rm = T))

survival <- survival %>%
  group_by(time) %>%
  mutate(
    run = as.numeric(run),
    homeowner_mean = mean(Homeowner, na.rm = T),
    renter_mean = mean(Renter, na.rm = T),
    diff_mean = mean(diff, na.rm = T),
    diff_lower = diff_mean - 1.96 * sd(diff, na.rm = T),
    diff_upper = diff_mean + 1.96 * sd(diff, na.rm = T))

diff <- survival %>% 
  select(time, diff_mean, diff_lower, diff_upper) %>% 
  unique() %>% 
  mutate(
    lower = diff_lower,
    upper = diff_upper,
    sig = case_when(lower > 0 | upper < 0 ~ "yes", T ~ "no"))
```

```{r}
plot_1 <- ggplot(survival, aes(x = time - 0.5)) +
  geom_step(aes(y = 1 - Renter, group = run), color = "darkblue", size = 0.2, alpha = 0.1) +
  geom_step(aes(y = 1 - renter_mean, color = "Renter"), size = 0.8) +
  geom_step(aes(y = 1 - Homeowner, group = run), color = "darkred", size = 0.2, alpha = 0.1) +
  geom_step(aes(y = 1 - homeowner_mean, color = "Homeowner"), size = 0.8) +
  scale_color_manual(values = c("Renter" = "darkblue", "Homeowner" = "darkred")) +
  scale_x_continuous("Age", limits = c(49, 70), breaks = seq(50, 76, 5)) +
  scale_y_continuous("Share retired", breaks = seq(0, 1, 0.1), label = scales::percent) +
  theme_classic() +
  coord_cartesian(ylim = c(0,1)) +
  theme(axis.text.x = element_text(color = "black"),
        axis.text.y = element_text(color = "black"),
        panel.grid.major.y = element_line(colour = "grey", size = 0.1),
        panel.spacing.x = unit(0, "pt"),
        strip.placement = 'outside',
        strip.background = element_blank(),
        strip.text.x = element_text(colour = "black"),
        legend.position=c(.18,.87),
        legend.key = element_rect(colour = "transparent", fill = "transparent"),
        legend.background = element_rect(fill = 'transparent'),
        legend.title = element_blank())

plot_2 <- ggplot(diff, aes(x = time, y = diff_mean)) +
  geom_hline(yintercept = 0, size = 0.5, lty = 2, color = "red") +
  geom_line(color = "lightgrey") +
  geom_point(aes(color = sig)) +
  geom_errorbar(aes(ymin = lower, ymax = upper, color = sig)) +
  theme_classic() +
  coord_cartesian(ylim = c(-0.05,0.25), xlim = c(50, 70)) +
  scale_color_manual(values = c("lightgrey", "black")) +
  guides(colour = guide_legend(nrow = 2)) +
  theme(axis.text.x = element_text(color = "black"),
        axis.text.y = element_text(color = "black"),
        panel.grid.major.y = element_line(colour = "grey", size = 0.1),
        panel.spacing.x = unit(0, "pt"),
        strip.placement = 'outside',
        strip.background = element_blank(),
        legend.position="none") +
  scale_y_continuous("Difference in share retired", label = scales::percent, breaks = seq(-5, 5, 0.02)) +
  scale_x_continuous("Age", breaks = seq(50, 70, 5))

plot_long <- grid.arrange(plot_1, plot_2, nrow = 2)
plot_wide <- grid.arrange(plot_1, plot_2, nrow = 1, top = textGrob("Male population \n", gp = gpar(fontsize = 16, fontface = 'bold')))

ggsave("plot_long.png", height = 9, width = 4, plot_long)
ggsave("plot_wide.png", height = 5.5, width = 8, plot_wide)

save.image("intervention.RData")

```

```{r}
```
