
```{r setup}
library(tidyverse)
library(survival)
library(ggsurvfit)
library(stargazer)
library(broom)
library(gesttools)
library(eha)

rm(list = ls())

load("data_final.RData") 

data <- data %>% filter(country == "Germany")

data <- data %>% select("person_id", "retired", "enter", "exit", "age", "sex", "homeowner", "homeowner_type", "homeowner_lag", "homeowner_type_lag", "education_level", "industry_lag", "marital_status_lag", "household_size_lag", "health_status_lag", "region", "migrant", "year") %>% na.omit()

data$homeowner <- as.factor(data$homeowner)
data$homeowner_type <- as.factor(data$homeowner_type)
data$homeowner_lag <- as.factor(data$homeowner_lag)
data$homeowner_type_lag <- as.factor(data$homeowner_type_lag)
data$education_level <- as.factor(data$education_level)
data$household_size_lag <- as.numeric(data$household_size_lag)
data$industry_lag <- as.factor(data$industry_lag)
data$marital_status_lag <- as.factor(data$marital_status_lag)
data$health_status_lag <- as.factor(data$health_status_lag)
data$region <- as.factor(data$region)
data$migrant <- as.factor(data$migrant)

data <- data %>% filter(year %in% c(1991:2020))
```

# Analysis: Kaplan-Meier curves

```{r}
# Total population
plot <- survfit2(Surv(enter, exit, retired) ~ homeowner, data) |> ggsurvfit()
plot <- plot$data
plot <- plot %>% filter(time %in% c(49:70)) %>% select(time, estimate, strata)
ggplot(plot, aes(x = time, y = 1 - estimate, color = strata, group = strata)) +
  geom_step() +
  scale_x_continuous("Age", limits = c(50, 70), breaks = seq(50, 76, 5)) +
  scale_y_continuous("Share retired", breaks = seq(0, 1, 0.1), label = scales::percent) +
  scale_color_manual(values = c("darkblue", "darkred", "darkgreen")) +
  scale_fill_manual(values = c("darkblue", "darkred", "darkgreen")) +
  theme_classic() +
  coord_cartesian(ylim = c(0,1)) +
  theme(axis.text.x = element_text(color = "black"),
        axis.text.y = element_text(color = "black"),
        panel.grid.major.y = element_line(colour = "grey", size = 0.1),
        panel.spacing.x = unit(0, "pt"),
        strip.placement = 'outside',
        strip.background = element_blank(),
        strip.text.x = element_text(colour = "black"),
        legend.position=c(.18,.86),
        legend.key = element_rect(colour = "transparent", fill = "transparent"),
        legend.background = element_rect(fill = 'transparent'),
        legend.title = element_blank()) +
  ggtitle("Total population")
ggsave("plots/plot_surv_1.png", height = 4, width = 5)

plot <- survfit2(Surv(enter, exit, retired) ~ homeowner_type, data) |> ggsurvfit()
plot <- plot$data
plot <- plot %>% filter(time %in% c(49:70)) %>% select(time, estimate, strata)
ggplot(plot, aes(x = time, y = 1 - estimate, color = strata, group = strata)) +
  geom_step() +
  scale_x_continuous("Age", limits = c(50, 70), breaks = seq(50, 76, 5)) +
  scale_y_continuous("Share retired", breaks = seq(0, 1, 0.1), label = scales::percent) +
  scale_color_manual(values = c("darkblue", "darkred", "darkgreen")) +
  scale_fill_manual(values = c("darkblue", "darkred", "darkgreen")) +
  theme_classic() +
  coord_cartesian(ylim = c(0,1)) +
  theme(axis.text.x = element_text(color = "black"),
        axis.text.y = element_text(color = "black"),
        panel.grid.major.y = element_line(colour = "grey", size = 0.1),
        panel.spacing.x = unit(0, "pt"),
        strip.placement = 'outside',
        strip.background = element_blank(),
        strip.text.x = element_text(colour = "black"),
        legend.position=c(.18,.86),
        legend.key = element_rect(colour = "transparent", fill = "transparent"),
        legend.background = element_rect(fill = 'transparent'),
        legend.title = element_blank()) +
  ggtitle("Total population")
ggsave("plots/plot_surv_2.png", height = 4, width = 5)

# Male population

plot <- survfit2(Surv(enter, exit, retired) ~ homeowner, data |> dplyr::filter(sex == "Male")) |> ggsurvfit()
plot <- plot$data
plot <- plot %>% filter(time %in% c(49:70)) %>% select(time, estimate, strata)
ggplot(plot, aes(x = time, y = 1 - estimate, color = strata, group = strata)) +
  geom_step() +
  scale_x_continuous("Age", limits = c(50, 70), breaks = seq(50, 76, 5)) +
  scale_y_continuous("Share retired", breaks = seq(0, 1, 0.1), label = scales::percent) +
  scale_color_manual(values = c("darkblue", "darkred", "darkgreen")) +
  scale_fill_manual(values = c("darkblue", "darkred", "darkgreen")) +
  theme_classic() +
  coord_cartesian(ylim = c(0,1)) +
  theme(axis.text.x = element_text(color = "black"),
        axis.text.y = element_text(color = "black"),
        panel.grid.major.y = element_line(colour = "grey", size = 0.1),
        panel.spacing.x = unit(0, "pt"),
        strip.placement = 'outside',
        strip.background = element_blank(),
        strip.text.x = element_text(colour = "black"),
        legend.position=c(.18,.86),
        legend.key = element_rect(colour = "transparent", fill = "transparent"),
        legend.background = element_rect(fill = 'transparent'),
        legend.title = element_blank()) +
  ggtitle("Male population")
ggsave("plots/plot_surv_3.png", height = 4, width = 5)

plot <- survfit2(Surv(enter, exit, retired) ~ homeowner_type, data |> dplyr::filter(sex == "Male")) |> ggsurvfit()
plot <- plot$data
plot <- plot %>% filter(time %in% c(49:70)) %>% select(time, estimate, strata)
ggplot(plot, aes(x = time, y = 1 - estimate, color = strata, group = strata)) +
  geom_step() +
  scale_x_continuous("Age", limits = c(50, 70), breaks = seq(50, 76, 5)) +
  scale_y_continuous("Share retired", breaks = seq(0, 1, 0.1), label = scales::percent) +
  scale_color_manual(values = c("darkblue", "darkred", "darkgreen")) +
  scale_fill_manual(values = c("darkblue", "darkred", "darkgreen")) +
  theme_classic() +
  coord_cartesian(ylim = c(0,1)) +
  theme(axis.text.x = element_text(color = "black"),
        axis.text.y = element_text(color = "black"),
        panel.grid.major.y = element_line(colour = "grey", size = 0.1),
        panel.spacing.x = unit(0, "pt"),
        strip.placement = 'outside',
        strip.background = element_blank(),
        strip.text.x = element_text(colour = "black"),
        legend.position=c(.18,.86),
        legend.key = element_rect(colour = "transparent", fill = "transparent"),
        legend.background = element_rect(fill = 'transparent'),
        legend.title = element_blank()) +
  ggtitle("Male population")
ggsave("plots/plot_surv_4.png", height = 4, width = 5)

plot <- survfit2(Surv(enter, exit, retired) ~ 1, data |> dplyr::filter(sex == "Male")) |> ggsurvfit()
plot <- plot$data
plot <- plot %>% filter(time %in% c(49:70)) %>% select(time, estimate)
ggplot(plot, aes(x = time, y = 1 - estimate)) +
  geom_step() +
  scale_x_continuous("Age", limits = c(50, 70), breaks = seq(50, 76, 5)) +
  scale_y_continuous("Share retired", breaks = seq(0, 1, 0.1), label = scales::percent) +
  scale_color_manual(values = c("darkblue", "darkred", "darkgreen")) +
  scale_fill_manual(values = c("darkblue", "darkred", "darkgreen")) +
  theme_classic() +
  coord_cartesian(ylim = c(0,1)) +
  theme(axis.text.x = element_text(color = "black"),
        axis.text.y = element_text(color = "black"),
        panel.grid.major.y = element_line(colour = "grey", size = 0.1),
        panel.spacing.x = unit(0, "pt"),
        strip.placement = 'outside',
        strip.background = element_blank(),
        strip.text.x = element_text(colour = "black"),
        legend.position=c(.18,.86),
        legend.key = element_rect(colour = "transparent", fill = "transparent"),
        legend.background = element_rect(fill = 'transparent'),
        legend.title = element_blank()) +
  ggtitle("Male population")
ggsave("plots/plot_surv_7.png", height = 4, width = 5)

# Female population

plot <- survfit2(Surv(enter, exit, retired) ~ homeowner, data |> dplyr::filter(sex == "Female")) |> ggsurvfit()
plot <- plot$data
plot <- plot %>% filter(time %in% c(49:70)) %>% select(time, estimate, strata)
ggplot(plot, aes(x = time, y = 1 - estimate, color = strata, group = strata)) +
  geom_step() +
  scale_x_continuous("Age", limits = c(50, 70), breaks = seq(50, 76, 5)) +
  scale_y_continuous("Share retired", breaks = seq(0, 1, 0.1), label = scales::percent) +
  scale_color_manual(values = c("darkblue", "darkred", "darkgreen")) +
  scale_fill_manual(values = c("darkblue", "darkred", "darkgreen")) +
  theme_classic() +
  coord_cartesian(ylim = c(0,1)) +
  theme(axis.text.x = element_text(color = "black"),
        axis.text.y = element_text(color = "black"),
        panel.grid.major.y = element_line(colour = "grey", size = 0.1),
        panel.spacing.x = unit(0, "pt"),
        strip.placement = 'outside',
        strip.background = element_blank(),
        strip.text.x = element_text(colour = "black"),
        legend.position=c(.18,.86),
        legend.key = element_rect(colour = "transparent", fill = "transparent"),
        legend.background = element_rect(fill = 'transparent'),
        legend.title = element_blank()) +
  ggtitle("Female population")
ggsave("plots/plot_surv_5.png", height = 4, width = 5)

plot <- survfit2(Surv(enter, exit, retired) ~ homeowner_type, data |> dplyr::filter(sex == "Female")) |> ggsurvfit()
plot <- plot$data
plot <- plot %>% filter(time %in% c(49:70)) %>% select(time, estimate, strata)
ggplot(plot, aes(x = time, y = 1 - estimate, color = strata, group = strata)) +
  geom_step() +
  scale_x_continuous("Age", limits = c(50, 70), breaks = seq(50, 76, 5)) +
  scale_y_continuous("Share retired", breaks = seq(0, 1, 0.1), label = scales::percent) +
  scale_color_manual(values = c("darkblue", "darkred", "darkgreen")) +
  scale_fill_manual(values = c("darkblue", "darkred", "darkgreen")) +
  theme_classic() +
  coord_cartesian(ylim = c(0,1)) +
  theme(axis.text.x = element_text(color = "black"),
        axis.text.y = element_text(color = "black"),
        panel.grid.major.y = element_line(colour = "grey", size = 0.1),
        panel.spacing.x = unit(0, "pt"),
        strip.placement = 'outside',
        strip.background = element_blank(),
        strip.text.x = element_text(colour = "black"),
        legend.position=c(.18,.86),
        legend.key = element_rect(colour = "transparent", fill = "transparent"),
        legend.background = element_rect(fill = 'transparent'),
        legend.title = element_blank()) +
  ggtitle("Female population")
ggsave("plots/plot_surv_6.png", height = 4, width = 5)

plot <- survfit2(Surv(enter, exit, retired) ~ 1, data |> dplyr::filter(sex == "Female")) |> ggsurvfit()
plot <- plot$data
plot <- plot %>% filter(time %in% c(49:70)) %>% select(time, estimate)
ggplot(plot, aes(x = time, y = 1 - estimate)) +
  geom_step() +
  scale_x_continuous("Age", limits = c(50, 70), breaks = seq(50, 76, 5)) +
  scale_y_continuous("Share retired", breaks = seq(0, 1, 0.1), label = scales::percent) +
  scale_color_manual(values = c("darkblue", "darkred", "darkgreen")) +
  scale_fill_manual(values = c("darkblue", "darkred", "darkgreen")) +
  theme_classic() +
  coord_cartesian(ylim = c(0,1)) +
  theme(axis.text.x = element_text(color = "black"),
        axis.text.y = element_text(color = "black"),
        panel.grid.major.y = element_line(colour = "grey", size = 0.1),
        panel.spacing.x = unit(0, "pt"),
        strip.placement = 'outside',
        strip.background = element_blank(),
        strip.text.x = element_text(colour = "black"),
        legend.position=c(.18,.86),
        legend.key = element_rect(colour = "transparent", fill = "transparent"),
        legend.background = element_rect(fill = 'transparent'),
        legend.title = element_blank()) +
  ggtitle("Female population")
ggsave("plots/plot_surv_8.png", height = 4, width = 5)
```

```{r}
rm(list=ls()[! ls() %in% c("data")])
```

```{r}
formula_1a <- as.formula("Surv(enter, exit, retired) ~ homeowner_lag + as.factor(year)")

formula_1b <- as.formula("Surv(enter, exit, retired) ~ homeowner_type_lag + as.factor(year)")

formula_2a <- as.formula("Surv(enter, exit, retired) ~ homeowner_lag + education_level + industry_lag + marital_status_lag + household_size_lag + health_status_lag + region + migrant + as.factor(year)")

formula_2b <- as.formula("Surv(enter, exit, retired) ~ homeowner_type_lag + education_level + industry_lag + marital_status_lag + household_size_lag + health_status_lag + region + migrant + as.factor(year)")
```

# Cox PH models

## Analysis

```{r}
cph_1 <- coxph(formula_1a, data = data |> dplyr::filter(sex == "Male"))

cph_2 <- coxph(formula_1a, data = data |> dplyr::filter(sex == "Female"))

cph_3 <- coxph(formula_2a, data = data |> dplyr::filter(sex == "Male"))

cph_4 <- coxph(formula_2a, data = data |> dplyr::filter(sex == "Female"))

cph_5 <- coxph(formula_1b, data = data |> dplyr::filter(sex == "Male"))

cph_6 <- coxph(formula_1b, data = data |> dplyr::filter(sex == "Female"))

cph_7 <- coxph(formula_2b, data = data |> dplyr::filter(sex == "Male"))

cph_8 <- coxph(formula_2b, data = data |> dplyr::filter(sex == "Female"))
```

# Testing proportional hazards

```{r}
# cox.zph(cph_1)
# cox.zph(cph_2)
# cox.zph(cph_3)
# cox.zph(cph_4)
# cox.zph(cph_5)
# cox.zph(cph_6)
# cox.zph(cph_7)
# cox.zph(cph_8)
```

## Results: Regression tables

```{r warning = F}
stargazer(cph_1, cph_2, cph_3, cph_4, type = "text", keep = "homeowner")

stargazer(cph_5, cph_6, cph_7, cph_8, type = "text", keep = "homeowner_type")
```

## Results: Coefficient plots

```{r}
cph_1 <- cph_1 %>% tidy() %>% dplyr::filter(term == "homeowner_lagHomeowner") %>%
  mutate(
    model = "All homeowners vs. Renters",
    estimate = round(exp(estimate), 2),
    label_1 = "Male population",
    label_2 = "Naïve",
    label_3 = paste0(estimate, "***"),
    lower95 = estimate - std.error * 1.96,
    upper95 = estimate + std.error * 1.96,
    lower90 = estimate - std.error * 1.65,
    upper90 = estimate + std.error * 1.65) %>%
  dplyr::select(model, label_1, label_2, label_3, estimate, lower95, upper95, lower90, upper90)

cph_2 <- cph_2 %>% tidy() %>% dplyr::filter(term == "homeowner_lagHomeowner") %>%
  mutate(
    model = "All homeowners vs. Renters",
    estimate = round(exp(estimate), 2),
    label_1 = "Male population",
    label_2 = "Adjusted",
    label_3 = paste0(estimate, "***"),
    lower95 = estimate - std.error * 1.96,
    upper95 = estimate + std.error * 1.96,
    lower90 = estimate - std.error * 1.65,
    upper90 = estimate + std.error * 1.65) %>%
  dplyr::select(model, label_1, label_2, label_3, estimate, lower95, upper95, lower90, upper90)

cph_3 <- cph_3 %>% tidy() %>% dplyr::filter(term == "homeowner_lagHomeowner") %>%
  mutate(
    model = "All homeowners vs. Renters",
    estimate = round(exp(estimate), 2),
    label_1 = "Female population",
    label_2 = "Naïve",
    label_3 = paste0(estimate, "***"),
    lower95 = estimate - std.error * 1.96,
    upper95 = estimate + std.error * 1.96,
    lower90 = estimate - std.error * 1.65,
    upper90 = estimate + std.error * 1.65) %>%
  dplyr::select(model, label_1, label_2, label_3, estimate, lower95, upper95, lower90, upper90)

cph_4 <- cph_4 %>% tidy() %>% dplyr::filter(term == "homeowner_lagHomeowner") %>%
  mutate(
    model = "All homeowners vs. Renters",
    estimate = round(exp(estimate), 2),
    label_1 = "Female population",
    label_2 = "Adjusted",
    label_3 = paste0(estimate, "***"),
    lower95 = estimate - std.error * 1.96,
    upper95 = estimate + std.error * 1.96,
    lower90 = estimate - std.error * 1.65,
    upper90 = estimate + std.error * 1.65) %>%
  dplyr::select(model, label_1, label_2, label_3, estimate, lower95, upper95, lower90, upper90)

plot_data <- rbind(cph_1, cph_2, cph_3, cph_4)

plot_data$order <- factor(c(1, 2, 3, 4))

plot_data$label_2 <- factor(plot_data$label_2, levels = unique(plot_data$label_2[order(plot_data$order)]))

plot_data$order <- factor(c(1, 1, 2, 2))

plot_data$label_1 <- factor(plot_data$label_1, levels = unique(plot_data$label_1[order(plot_data$order)]))

ggplot(plot_data, aes(color = model)) +
  geom_hline(yintercept = 1, size = 0.3, lty = 2) +
  geom_point(aes(x = label_2, y = estimate), position = position_dodge(width = 0.3), size = 1.5) +
  geom_linerange(aes(x = label_2, ymin = lower90, ymax = upper90), lwd = 1, position = position_dodge(width = 0.3)) +
  geom_linerange(aes(x = label_2, ymin = lower95, ymax = upper95), lwd = 1/2, position = position_dodge(width = 0.3)) +
  geom_text(aes(x = label_2,  y = estimate, label = label_3), hjust = -0.2, size = 3, position = position_dodge(width = 0.3)) +
  facet_grid(.~ label_1, space = 'free_x', scales = 'free_x', switch = 'x') +
  scale_x_discrete(element_blank()) +
  scale_y_continuous(element_blank(), breaks = seq(0, 5, 0.2)) +
  scale_color_manual(values = c("black")) +
  theme_classic() +
  coord_cartesian(ylim = c(0.6,2.6)) +
  guides(colour = guide_legend(nrow = 2)) +
  theme(axis.text.x = element_text(color = "black"),
        axis.text.y = element_text(color = "black"),
        panel.grid.major.y = element_line(colour = "grey", size = 0.1),
        panel.spacing.x = unit(0, "pt"),
        strip.placement = 'outside',
        strip.background = element_blank(),
        strip.text.x = element_text(colour = "black"),
        legend.position=c(.28,.9),
        legend.key = element_rect(colour = "transparent", fill = "transparent"),
        legend.background = element_rect(fill = 'transparent'),
        legend.title = element_blank())
  #scale_y_log10(element_blank(), limits = c(0.3, 2), expand = c(0, 0), breaks = seq(-100, 100, by = 0.2))

ggsave("plots/plot_cph_1.png", height = 4.2, width = 4)
```

```{r}
cph_5 <- cph_5 %>% tidy() %>% dplyr::filter(term %in% c("homeowner_type_lagMortgage", "homeowner_type_lagNo_mortgage")) %>%
  mutate(
    model = c("Mortgage-paying homeowners vs. Renters", "Mortgage-free homeowners vs. Renters"),
    estimate = round(exp(estimate), 2),
    label_1 = c("Male population", "Male population"),
    label_2 = c("Naïve", "Naïve"),
    sig = c("***", "***"),
    label_3 = paste0(estimate, sig),
    lower95 = estimate - std.error * 1.96,
    upper95 = estimate + std.error * 1.96,
    lower90 = estimate - std.error * 1.65,
    upper90 = estimate + std.error * 1.65) %>%
  dplyr::select(model, label_1, label_2, label_3, estimate, lower95, upper95, lower90, upper90)

cph_6 <- cph_6 %>% tidy() %>% dplyr::filter(term %in% c("homeowner_type_lagMortgage", "homeowner_type_lagNo_mortgage")) %>%
  mutate(
    model = c("Mortgage-paying homeowners vs. Renters", "Mortgage-free homeowners vs. Renters"),
    estimate = round(exp(estimate), 2),
    label_1 = c("Male population", "Male population"),
    label_2 = c("Adjusted", "Adjusted"),
    sig = c("***", "***"),
    label_3 = paste0(estimate, sig),
    lower95 = estimate - std.error * 1.96,
    upper95 = estimate + std.error * 1.96,
    lower90 = estimate - std.error * 1.65,
    upper90 = estimate + std.error * 1.65) %>%
  dplyr::select(model, label_1, label_2, label_3, estimate, lower95, upper95, lower90, upper90)

cph_7 <- cph_7 %>% tidy() %>% dplyr::filter(term %in% c("homeowner_type_lagMortgage", "homeowner_type_lagNo_mortgage")) %>%
  mutate(
    model = c("Mortgage-paying homeowners vs. Renters", "Mortgage-free homeowners vs. Renters"),
    estimate = round(exp(estimate), 2),
    label_1 = c("Female population", "Female population"),
    label_2 = c("Naïve", "Naïve"),
    sig = c("***", "***"),
    label_3 = paste0(estimate, sig),
    lower95 = estimate - std.error * 1.96,
    upper95 = estimate + std.error * 1.96,
    lower90 = estimate - std.error * 1.65,
    upper90 = estimate + std.error * 1.65) %>%
  dplyr::select(model, label_1, label_2, label_3, estimate, lower95, upper95, lower90, upper90)

cph_8 <- cph_8 %>% tidy() %>% dplyr::filter(term %in% c("homeowner_type_lagMortgage", "homeowner_type_lagNo_mortgage")) %>%
  mutate(
    model = c("Mortgage-paying homeowners vs. Renters", "Mortgage-free homeowners vs. Renters"),
    estimate = round(exp(estimate), 2),
    label_1 = c("Female population", "Female population"),
    label_2 = c("Adjusted", "Adjusted"),
    sig = c("***", "***"),
    label_3 = paste0(estimate, sig),
    lower95 = estimate - std.error * 1.96,
    upper95 = estimate + std.error * 1.96,
    lower90 = estimate - std.error * 1.65,
    upper90 = estimate + std.error * 1.65) %>%
  dplyr::select(model, label_1, label_2, label_3, estimate, lower95, upper95, lower90, upper90)

plot_data_2 <- rbind(cph_5, cph_6, cph_7, cph_8)

plot_data_2$order <- factor(c(1, 2, 3, 4, 5, 6, 7, 8))

plot_data_2$label_2 <- factor(plot_data_2$label_2, levels = unique(plot_data_2$label_2[order(plot_data_2$order)]))

plot_data_2$order <- factor(c(1, 1, 2, 2, 1, 1, 2, 2))

plot_data_2$label_1 <- factor(plot_data_2$label_1, levels = unique(plot_data_2$label_1[order(plot_data_2$order)]))

ggplot(plot_data_2, aes(color = model)) +
  geom_hline(yintercept = 1, size = 0.3, lty = 2) +
  geom_point(aes(x = label_2, y = estimate), position = position_dodge(width = 0.3), size = 1.5) +
  geom_linerange(aes(x = label_2, ymin = lower90, ymax = upper90), lwd = 1, position = position_dodge(width = 0.3)) +
  geom_linerange(aes(x = label_2, ymin = lower95, ymax = upper95), lwd = 1/2, position = position_dodge(width = 0.3)) +
  geom_text(aes(x = label_2,  y = estimate, label = label_3), hjust = -0.2, size = 3, position = position_dodge(width = 0.3)) +
  facet_grid(.~ label_1, space = 'free_x', scales = 'free_x', switch = 'x') +
  scale_x_discrete(element_blank()) +
  scale_y_continuous(element_blank(), breaks = seq(0, 5, 0.2)) +
  scale_color_manual(values = c("darkblue", "darkred")) +
  theme_classic() +
  coord_cartesian(ylim = c(0.6,2.6)) +
  guides(colour = guide_legend(nrow = 2)) +
  theme(axis.text.x = element_text(color = "black"),
        axis.text.y = element_text(color = "black"),
        panel.grid.major.y = element_line(colour = "grey", size = 0.1),
        panel.spacing.x = unit(0, "pt"),
        strip.placement = 'outside',
        strip.background = element_blank(),
        strip.text.x = element_text(colour = "black"),
        legend.position=c(.4,.9),
        legend.key = element_rect(colour = "transparent", fill = "transparent"),
        legend.background = element_rect(fill = 'transparent'),
        legend.title = element_blank()) 

ggsave("plots/plot_cph_2.png", height = 4.2, width = 4)
```

```{r}
rm(list=ls()[! ls() %in% c("data", "formula_1a", "formula_1b", "formula_2a", "formula_2b")])
```

# Piecewise constant hazard models

## Analysis

```{r}
model_1 <- pchreg(formula_1a, data = data |> dplyr::filter(sex == "Male"), cuts = c(50, 55, 59, 60, 64, 65, 70))
model_1 <- regtable(summary(model_1), short = T) %>% 
  filter(level %in% c("Homeowner")) %>% 
  mutate(variable = level, estimate = as.numeric(Coef), se = as.numeric(SE), 
         lower95 = exp(estimate - 1.96 * se), upper95 = exp(estimate + 1.96 * se), 
         lower90 = exp(estimate - 1.65 * se), upper90 = exp(estimate + 1.65 * se), 
         estimate = exp(estimate),
         model = "All homeowners vs. Renters",
         label_1 = "Male population",
         label_2 = "Naïve",
         label_3 = paste0(round(estimate, 2), "***")) %>%
  select(model, label_1, label_2, label_3, estimate, lower95, upper95, lower90, upper90)

model_2 <- pchreg(formula_1a, data = data |> dplyr::filter(sex == "Female"), cuts = c(50, 55, 59, 60, 64, 65, 70))
model_2 <- regtable(summary(model_2), short = T) %>% 
  filter(level %in% c("Homeowner")) %>% 
  mutate(variable = level, estimate = as.numeric(Coef), se = as.numeric(SE), 
         lower95 = exp(estimate - 1.96 * se), upper95 = exp(estimate + 1.96 * se), 
         lower90 = exp(estimate - 1.65 * se), upper90 = exp(estimate + 1.65 * se), 
         estimate = exp(estimate),
         model = "All homeowners vs. Renters",
         label_1 = "Female population",
         label_2 = "Naïve",
         label_3 = paste0(round(estimate, 2), "***")) %>%
  select(model, label_1, label_2, label_3, estimate, lower95, upper95, lower90, upper90)

model_3 <- pchreg(formula_2a, data = data |> dplyr::filter(sex == "Male"), cuts = c(50, 55, 59, 60, 64, 65, 70))
model_3 <- regtable(summary(model_3), short = T) %>% 
  filter(level %in% c("Homeowner")) %>% 
  mutate(variable = level, estimate = as.numeric(Coef), se = as.numeric(SE), 
         lower95 = exp(estimate - 1.96 * se), upper95 = exp(estimate + 1.96 * se), 
         lower90 = exp(estimate - 1.65 * se), upper90 = exp(estimate + 1.65 * se), 
         estimate = exp(estimate),
         model = "All homeowners vs. Renters",
         label_1 = "Male population",
         label_2 = "Adjusted",
         label_3 = paste0(round(estimate, 2), "***")) %>%
  select(model, label_1, label_2, label_3, estimate, lower95, upper95, lower90, upper90)

model_4 <- pchreg(formula_2a, data = data |> dplyr::filter(sex == "Female" & year != 2014), cuts = c(50, 55, 59, 60, 64, 65, 70))
model_4 <- regtable(summary(model_4), short = T) %>% 
  filter(level %in% c("Homeowner")) %>% 
  mutate(variable = level, estimate = as.numeric(Coef), se = as.numeric(SE), 
         lower95 = exp(estimate - 1.96 * se), upper95 = exp(estimate + 1.96 * se), 
         lower90 = exp(estimate - 1.65 * se), upper90 = exp(estimate + 1.65 * se), 
         estimate = exp(estimate),
         model = "All homeowners vs. Renters",
         label_1 = "Female population",
         label_2 = "Adjusted",
         label_3 = paste0(round(estimate, 2), "***")) %>%
  select(model, label_1, label_2, label_3, estimate, lower95, upper95, lower90, upper90)

plot_data <- rbind(model_1, model_2, model_3, model_4)

plot_data$order <- factor(c(1, 2, 3, 4))

plot_data$label_2 <- factor(plot_data$label_2, levels = unique(plot_data$label_2[order(plot_data$order)]))

plot_data$order <- factor(c(1, 1, 2, 2))

plot_data$label_1 <- factor(plot_data$label_1, levels = unique(plot_data$label_1[order(plot_data$order)]))

ggplot(plot_data, aes(color = model)) +
  geom_hline(yintercept = 1, size = 0.3, lty = 2) +
  geom_point(aes(x = label_2, y = estimate), position = position_dodge(width = 0.3), size = 1.5) +
  geom_linerange(aes(x = label_2, ymin = lower90, ymax = upper90), lwd = 1, position = position_dodge(width = 0.3)) +
  geom_linerange(aes(x = label_2, ymin = lower95, ymax = upper95), lwd = 1/2, position = position_dodge(width = 0.3)) +
  geom_text(aes(x = label_2,  y = estimate, label = label_3), hjust = -0.2, size = 3, position = position_dodge(width = 0.3)) +
  facet_grid(.~ label_1, space = 'free_x', scales = 'free_x', switch = 'x') +
  scale_x_discrete(element_blank()) +
  scale_y_continuous(element_blank(), breaks = seq(0, 5, 0.2)) +
  scale_color_manual(values = c("black")) +
  theme_classic() +
  coord_cartesian(ylim = c(0.6,2.6)) +
  guides(colour = guide_legend(nrow = 2)) +
  theme(axis.text.x = element_text(color = "black"),
        axis.text.y = element_text(color = "black"),
        panel.grid.major.y = element_line(colour = "grey", size = 0.1),
        panel.spacing.x = unit(0, "pt"),
        strip.placement = 'outside',
        strip.background = element_blank(),
        strip.text.x = element_text(colour = "black"),
        legend.position=c(.28,.9),
        legend.key = element_rect(colour = "transparent", fill = "transparent"),
        legend.background = element_rect(fill = 'transparent'),
        legend.title = element_blank())
ggsave("plots/plot_pchm_1.png", height = 4.2, width = 4)
```

```{r}
model_1 <- pchreg(formula_1b, data = data |> dplyr::filter(sex == "Male"), cuts = c(50, 55, 59, 60, 64, 65, 70))
model_1 <- regtable(summary(model_1), short = T) %>% 
  filter(level %in% c("Mortgage", "No_mortgage")) %>% 
  mutate(variable = level, estimate = as.numeric(Coef), se = as.numeric(SE), 
         lower95 = exp(estimate - 1.96 * se), upper95 = exp(estimate + 1.96 * se), 
         lower90 = exp(estimate - 1.65 * se), upper90 = exp(estimate + 1.65 * se), 
         estimate = exp(estimate),
         model = c("Mortgage-paying homeowners vs. Renters", "Mortgage-free homeowners vs. Renters"),
         estimate = round(estimate, 2),
         label_1 = c("Male population", "Male population"),
         label_2 = c("Naïve", "Naïve"),
         sig = c("***", "***"),
         label_3 = paste0(estimate, sig)) %>%
  select(model, label_1, label_2, label_3, estimate, lower95, upper95, lower90, upper90)

model_2 <- pchreg(formula_1b, data = data |> dplyr::filter(sex == "Female"), cuts = c(50, 55, 59, 60, 64, 65, 70))
model_2 <- regtable(summary(model_2), short = T) %>% 
  filter(level %in% c("Mortgage", "No_mortgage")) %>% 
  mutate(variable = level, estimate = as.numeric(Coef), se = as.numeric(SE), 
         lower95 = exp(estimate - 1.96 * se), upper95 = exp(estimate + 1.96 * se), 
         lower90 = exp(estimate - 1.65 * se), upper90 = exp(estimate + 1.65 * se), 
         estimate = exp(estimate),
         model = c("Mortgage-paying homeowners vs. Renters", "Mortgage-free homeowners vs. Renters"),
         estimate = round(estimate, 2),
         label_1 = c("Female population", "Female population"),
         label_2 = c("Naïve", "Naïve"),
         sig = c("***", "***"),
         label_3 = paste0(estimate, sig)) %>%
  select(model, label_1, label_2, label_3, estimate, lower95, upper95, lower90, upper90)

model_3 <- pchreg(formula_2b, data = data |> dplyr::filter(sex == "Male"), cuts = c(50, 55, 59, 60, 64, 65, 70))
model_3 <- regtable(summary(model_3), short = T) %>% 
  filter(level %in% c("Mortgage", "No_mortgage")) %>% 
  mutate(variable = level, estimate = as.numeric(Coef), se = as.numeric(SE), 
         lower95 = exp(estimate - 1.96 * se), upper95 = exp(estimate + 1.96 * se), 
         lower90 = exp(estimate - 1.65 * se), upper90 = exp(estimate + 1.65 * se), 
         estimate = exp(estimate),
         model = c("Mortgage-paying homeowners vs. Renters", "Mortgage-free homeowners vs. Renters"),
         estimate = round(estimate, 2),
         label_1 = c("Male population", "Male population"),
         label_2 = c("Adjusted", "Adjusted"),
         sig = c("***", "***"),
         label_3 = paste0(estimate, sig)) %>%
  select(model, label_1, label_2, label_3, estimate, lower95, upper95, lower90, upper90)

model_4 <- pchreg(formula_2b, data = data |> dplyr::filter(sex == "Female"), cuts = c(50, 55, 59, 60, 64, 65, 70))
model_4 <- regtable(summary(model_4), short = T) %>% 
  filter(level %in% c("Mortgage", "No_mortgage")) %>% 
  mutate(variable = level, estimate = as.numeric(Coef), se = as.numeric(SE), 
         lower95 = exp(estimate - 1.96 * se), upper95 = exp(estimate + 1.96 * se), 
         lower90 = exp(estimate - 1.65 * se), upper90 = exp(estimate + 1.65 * se), 
         estimate = exp(estimate),
         model = c("Mortgage-paying homeowners vs. Renters", "Mortgage-free homeowners vs. Renters"),
         estimate = round(estimate, 2),
         label_1 = c("Female population", "Female population"),
         label_2 = c("Adjusted", "Adjusted"),
         sig = c("***", "***"),
         label_3 = paste0(estimate, sig)) %>%
  select(model, label_1, label_2, label_3, estimate, lower95, upper95, lower90, upper90)

plot_data_2 <- rbind(model_1, model_2, model_3, model_4)

plot_data_2$order <- factor(c(1, 2, 3, 4, 5, 6, 7, 8))

plot_data_2$label_2 <- factor(plot_data_2$label_2, levels = unique(plot_data_2$label_2[order(plot_data_2$order)]))

plot_data_2$order <- factor(c(1, 1, 2, 2, 1, 1, 2, 2))

plot_data_2$label_1 <- factor(plot_data_2$label_1, levels = unique(plot_data_2$label_1[order(plot_data_2$order)]))

ggplot(plot_data_2, aes(color = model)) +
  geom_hline(yintercept = 1, size = 0.3, lty = 2) +
  geom_point(aes(x = label_2, y = estimate), position = position_dodge(width = 0.3), size = 1.5) +
  geom_linerange(aes(x = label_2, ymin = lower90, ymax = upper90), lwd = 1, position = position_dodge(width = 0.3)) +
  geom_linerange(aes(x = label_2, ymin = lower95, ymax = upper95), lwd = 1/2, position = position_dodge(width = 0.3)) +
  geom_text(aes(x = label_2,  y = estimate, label = label_3), hjust = -0.2, size = 3, position = position_dodge(width = 0.3)) +
  facet_grid(.~ label_1, space = 'free_x', scales = 'free_x', switch = 'x') +
  scale_x_discrete(element_blank()) +
  scale_y_continuous(element_blank(), breaks = seq(0, 5, 0.2)) +
  scale_color_manual(values = c("darkblue", "darkred")) +
  theme_classic() +
  coord_cartesian(ylim = c(0.6,2.6)) +
  guides(colour = guide_legend(nrow = 2)) +
  theme(axis.text.x = element_text(color = "black"),
        axis.text.y = element_text(color = "black"),
        panel.grid.major.y = element_line(colour = "grey", size = 0.1),
        panel.spacing.x = unit(0, "pt"),
        strip.placement = 'outside',
        strip.background = element_blank(),
        strip.text.x = element_text(colour = "black"),
        legend.position=c(.4,.9),
        legend.key = element_rect(colour = "transparent", fill = "transparent"),
        legend.background = element_rect(fill = 'transparent'),
        legend.title = element_blank()) 
ggsave("plots/plot_pchm_2.png", height = 4.2, width = 4)
```

```{r}
```
